Config = Config or {}
Config.vehicles.boats = {
 ['squalo'] = {
  ['name'] = 'Squalo',
  ['brand'] = 'Shitzu',
  ['model'] = 'squalo',
  ['price'] = 40000,
  ['category'] = 'boats',
  ['categoryLabel'] = 'Boats',
  ['hash'] = `squalo`,
  ['shop'] = 'boats',
 },
 ['marquis'] = {
  ['name'] = 'Marquis',
  ['brand'] = 'Dinka',
  ['model'] = 'marquis',
  ['price'] = 40000,
  ['category'] = 'boats',
  ['categoryLabel'] = 'Boats',
  ['hash'] = `marquis`,
  ['shop'] = 'boats',
 },
 ['seashark'] = {
  ['name'] = 'Seashark',
  ['brand'] = 'Speedophile',
  ['model'] = 'seashark',
  ['price'] = 40000,
  ['category'] = 'boats',
  ['categoryLabel'] = 'Boats',
  ['hash'] = `seashark`,
  ['shop'] = 'boats',
 },
 ['seashark2'] = {
  ['name'] = 'Seashark Lifeguard',
  ['brand'] = 'Speedophile',
  ['model'] = 'seashark2',
  ['price'] = 40000,
  ['category'] = 'boats',
  ['categoryLabel'] = 'Boats',
  ['hash'] = `seashark2`,
  ['shop'] = 'boats',
 },
 ['seashark3'] = {
  ['name'] = 'Seashark Yacht',
  ['brand'] = 'Speedophile',
  ['model'] = 'seashark3',
  ['price'] = 40000,
  ['category'] = 'boats',
  ['categoryLabel'] = 'Boats',
  ['hash'] = `seashark3`,
  ['shop'] = 'boats',
 },
 ['jetmax'] = {
  ['name'] = 'Jetmax',
  ['brand'] = 'Shitzu',
  ['model'] = 'jetmax',
  ['price'] = 40000,
  ['category'] = 'boats',
  ['categoryLabel'] = 'Boats',
  ['hash'] = `jetmax`,
  ['shop'] = 'boats',
 },
 ['tropic'] = {
  ['name'] = 'Tropic',
  ['brand'] = 'Shitzu',
  ['model'] = 'tropic',
  ['price'] = 40000,
  ['category'] = 'boats',
  ['categoryLabel'] = 'Boats',
  ['hash'] = `tropic`,
  ['shop'] = 'boats',
 },
 ['tropic2'] = {
  ['name'] = 'Tropic Yacht',
  ['brand'] = 'Shitzu',
  ['model'] = 'tropic2',
  ['price'] = 40000,
  ['category'] = 'boats',
  ['categoryLabel'] = 'Boats',
  ['hash'] = `tropic2`,
  ['shop'] = 'boats',
 },
 ['dinghy'] = {
  ['name'] = 'Dinghy 2-Seater',
  ['brand'] = 'Nagasaki',
  ['model'] = 'dinghy',
  ['price'] = 40000,
  ['category'] = 'boats',
  ['categoryLabel'] = 'Boats',
  ['hash'] = `dinghy`,
  ['shop'] = 'boats',
 },
 ['dinghy2'] = {
  ['name'] = 'Dinghy 4-Seater',
  ['brand'] = 'Nagasaki',
  ['model'] = 'dinghy2',
  ['price'] = 40000,
  ['category'] = 'boats',
  ['categoryLabel'] = 'Boats',
  ['hash'] = `dinghy2`,
  ['shop'] = 'boats',
 },
 ['dinghy3'] = {
  ['name'] = 'Dinghy (Heist)',
  ['brand'] = 'Nagasaki',
  ['model'] = 'dinghy3',
  ['price'] = 40000,
  ['category'] = 'boats',
  ['categoryLabel'] = 'Boats',
  ['hash'] = `dinghy3`,
  ['shop'] = 'boats',
 },
 ['dinghy4'] = {
  ['name'] = 'Dinghy Yacht',
  ['brand'] = 'Nagasaki',
  ['model'] = 'dinghy4',
  ['price'] = 40000,
  ['category'] = 'boats',
  ['categoryLabel'] = 'Boats',
  ['hash'] = `dinghy4`,
  ['shop'] = 'boats',
 },
 ['suntrap'] = {
  ['name'] = 'Suntrap',
  ['brand'] = 'Shitzu',
  ['model'] = 'suntrap',
  ['price'] = 40000,
  ['category'] = 'boats',
  ['categoryLabel'] = 'Boats',
  ['hash'] = `suntrap`,
  ['shop'] = 'boats',
 },
 ['speeder'] = {
  ['name'] = 'Speeder',
  ['brand'] = 'Pegassi',
  ['model'] = 'speeder',
  ['price'] = 40000,
  ['category'] = 'boats',
  ['categoryLabel'] = 'Boats',
  ['hash'] = `speeder`,
  ['shop'] = 'boats',
 },
 ['speeder2'] = {
  ['name'] = 'Speeder Yacht',
  ['brand'] = 'Pegassi',
  ['model'] = 'speeder2',
  ['price'] = 40000,
  ['category'] = 'boats',
  ['categoryLabel'] = 'Boats',
  ['hash'] = `speeder2`,
  ['shop'] = 'boats',
 },
 ['longfin'] = {
  ['name'] = 'Longfin',
  ['brand'] = 'Shitzu',
  ['model'] = 'longfin',
  ['price'] = 40000,
  ['category'] = 'boats',
  ['categoryLabel'] = 'Boats',
  ['hash'] = `longfin`,
  ['shop'] = 'boats',
 },
 ['toro'] = {
  ['name'] = 'Toro',
  ['brand'] = 'Lampadati',
  ['model'] = 'toro',
  ['price'] = 40000,
  ['category'] = 'boats',
  ['categoryLabel'] = 'Boats',
  ['hash'] = `toro`,
  ['shop'] = 'boats',
 },
 ['toro2'] = {
  ['name'] = 'Toro Yacht',
  ['brand'] = 'Lampadati',
  ['model'] = 'toro2',
  ['price'] = 40000,
  ['category'] = 'boats',
  ['categoryLabel'] = 'Boats',
  ['hash'] = `toro2`,
  ['shop'] = 'boats',
 },
}