Config = Config or {}
Config.vehicles.commercial = {
 ['hauler'] = {
  ['name'] = 'Hauler',
  ['brand'] = 'Jobuilt',
  ['model'] = 'hauler',
  ['price'] = 100000,
  ['category'] = 'commercial',
  ["categoryLabel"] = 'Commercial',
  ['hash'] = `hauler`,
  ['shop'] = 'truck',
 },
 ['packer'] = {
  ['name'] = 'Packer',
  ['brand'] = 'MTL',
  ['model'] = 'packer',
  ['price'] = 100000,
  ['category'] = 'commercial',
  ["categoryLabel"] = 'Commercial',
  ['hash'] = `packer`,
  ['shop'] = 'truck',
 },
 ['stockade'] = {
  ['name'] = 'Stockade',
  ['brand'] = 'Brute',
  ['model'] = 'stockade',
  ['price'] = 100000,
  ['category'] = 'commercial',
  ["categoryLabel"] = 'Commercial',
  ['hash'] = `stockade`,
  ['shop'] = 'truck',
 },
 ['biff'] = {
  ['name'] = 'Biff',
  ['brand'] = 'Brute',
  ['model'] = 'biff',
  ['price'] = 100000,
  ['category'] = 'commercial',
  ["categoryLabel"] = 'Commercial',
  ['hash'] = `biff`,
  ['shop'] = 'truck',
 },
 ['phantom'] = {
  ['name'] = 'Phantom',
  ['brand'] = 'Jobuilt',
  ['model'] = 'phantom',
  ['price'] = 100000,
  ['category'] = 'commercial',
  ["categoryLabel"] = 'Commercial',
  ['hash'] = `phantom`,
  ['shop'] = 'truck',
 },
 ['phantom3'] = {
  ['name'] = 'Phantom Custom',
  ['brand'] = 'Jobuilt',
  ['model'] = 'phantom3',
  ['price'] = 110000,
  ['category'] = 'commercial',
  ["categoryLabel"] = 'Commercial',
  ['hash'] = `phantom3`,
  ['shop'] = 'truck',
 },
 ['benson'] = {
  ['name'] = 'Benson',
  ['brand'] = 'Vapid',
  ['model'] = 'benson',
  ['price'] = 55000,
  ['category'] = 'commercial',
  ["categoryLabel"] = 'Commercial',
  ['hash'] = `benson`,
  ['shop'] = 'truck',
 },
 ['mule'] = {
  ['name'] = 'Mule',
  ['brand'] = 'Maibatsu',
  ['model'] = 'mule',
  ['price'] = 40000,
  ['category'] = 'commercial',
  ["categoryLabel"] = 'Commercial',
  ['hash'] = `mule`,
  ['shop'] = 'truck',
 },
 ['mule2'] = {
  ['name'] = 'Mule with Drop Door',
  ['brand'] = 'Maibatsu',
  ['model'] = 'mule2',
  ['price'] = 40000,
  ['category'] = 'commercial',
  ["categoryLabel"] = 'Commercial',
  ['hash'] = `mule2`,
  ['shop'] = 'truck',
 },
 ['mule3'] = {
  ['name'] = 'Mule with Swinging Doors',
  ['brand'] = 'Maibatsu',
  ['model'] = 'mule3',
  ['price'] = 40000,
  ['category'] = 'commercial',
  ["categoryLabel"] = 'Commercial',
  ['hash'] = `mule3`,
  ['shop'] = 'truck',
 },
 ['mule4'] = {
  ['name'] = 'Mule with Swinging Doors & Side Step',
  ['brand'] = 'Maibatsu',
  ['model'] = 'mule4',
  ['price'] = 40000,
  ['category'] = 'commercial',
  ["categoryLabel"] = 'Commercial',
  ['hash'] = `mule4`,
  ['shop'] = 'truck',
 },
 ['mule5'] = {
  ['name'] = 'Mule with Swinging Doors & Step Bumper',
  ['brand'] = 'Maibatsu',
  ['model'] = 'mule5',
  ['price'] = 40000,
  ['category'] = 'commercial',
  ["categoryLabel"] = 'Commercial',
  ['hash'] = `mule5`,
  ['shop'] = 'truck',
 },
 ['pounder'] = {
  ['name'] = 'Pounder',
  ['brand'] = 'MTL',
  ['model'] = 'pounder',
  ['price'] = 55000,
  ['category'] = 'commercial',
  ["categoryLabel"] = 'Commercial',
  ['hash'] = `pounder`,
  ['shop'] = 'truck',
 },
}