Config = Config or {}
Config.vehicles.compacts = {
 ['asbo'] = { -- This has to match the spawn code of the vehicle
  ['name'] = 'Asbo', -- This is the display of the vehicle
  ['brand'] = 'Maxwell', -- This is the vehicle's brand (Ford, Chevrolet, BMW, Mercedes, etc)
  ['model'] = 'asbo', -- This must match the spawn code of the vehicle
  ['price'] = 4000, -- The price that the vehicle sells for
  ['category'] = 'compacts', -- This must match "VehicleClass" in vehicles.meta for the vehicle and must also exist in https://docs.fivem.net/natives/?_0x29439776AAA00A62
  ['categoryLabel'] = 'Compacts', -- Customize for your Vehicle Shop headings (can even include spaces)
  ['hash'] = `asbo`, -- This has to match the spawn code of the vehicle and must be surrounded by backticks. Example of a Backtick: `
  ['shop'] = 'pdm', -- Can be a single shop or multiple shops. For multiple shops for example {'shopname1','shopname2','shopname3'}
 },
 ['blista'] = {
  ['name'] = 'Blista',
  ['brand'] = 'Dinka',
  ['model'] = 'blista',
  ['price'] = 13000,
  ['category'] = 'compacts',
  ['categoryLabel'] = 'Compacts',
  ['hash'] = `blista`,
  ['shop'] = 'pdm',
 },
 ['brioso'] = {
  ['name'] = 'Brioso R/A',
  ['brand'] = 'Grotti',
  ['model'] = 'brioso',
  ['price'] = 20000,
  ['category'] = 'compacts',
  ['categoryLabel'] = 'Compacts',
  ['hash'] = `brioso`,
  ['shop'] = 'pdm',
 },
 ['club'] = {
  ['name'] = 'Club',
  ['brand'] = 'BF',
  ['model'] = 'club',
  ['price'] = 8000,
  ['category'] = 'compacts',
  ['categoryLabel'] = 'Compacts',
  ['hash'] = `club`,
  ['shop'] = 'pdm',
 },
 ['dilettante'] = {
  ['name'] = 'Dilettante',
  ['brand'] = 'Karin',
  ['model'] = 'dilettante',
  ['price'] = 9000,
  ['category'] = 'compacts',
  ['categoryLabel'] = 'Compacts',
  ['hash'] = `dilettante`,
  ['shop'] = 'pdm',
 },
 ['dilettante2'] = {
  ['name'] = 'Dilettante Patrol',
  ['brand'] = 'Karin',
  ['model'] = 'dilettante2',
  ['price'] = 12000,
  ['category'] = 'compacts',
  ['categoryLabel'] = 'Compacts',
  ['hash'] = `dilettante2`,
  ['shop'] = 'pdm',
 },
 ['kanjo'] = {
  ['name'] = 'Blista Kanjo',
  ['brand'] = 'Dinka',
  ['model'] = 'kanjo',
  ['price'] = 12000,
  ['category'] = 'compacts',
  ['categoryLabel'] = 'Compacts',
  ['hash'] = `kanjo`,
  ['shop'] = 'pdm',
 },
 ['issi2'] = {
  ['name'] = 'Issi',
  ['brand'] = 'Weeny',
  ['model'] = 'issi2',
  ['price'] = 7000,
  ['category'] = 'compacts',
  ['categoryLabel'] = 'Compacts',
  ['hash'] = `issi2`,
  ['shop'] = 'pdm',
 },
 ['issi3'] = {
  ['name'] = 'Issi Classic',
  ['brand'] = 'Weeny',
  ['model'] = 'issi3',
  ['price'] = 5000,
  ['category'] = 'compacts',
  ['categoryLabel'] = 'Compacts',
  ['hash'] = `issi3`,
  ['shop'] = 'pdm',
 },
 ['issi4'] = {
  ['name'] = 'Issi Arena',
  ['brand'] = 'Weeny',
  ['model'] = 'issi4',
  ['price'] = 80000,
  ['category'] = 'compacts',
  ['categoryLabel'] = 'Compacts',
  ['hash'] = `issi4`,
  ['shop'] = 'pdm',
 },
 ['issi5'] = {
  ['name'] = 'Issi Future Shock',
  ['brand'] = 'Weeny',
  ['model'] = 'issi5',
  ['price'] = 80000,
  ['category'] = 'compacts',
  ['categoryLabel'] = 'Compacts',
  ['hash'] = `issi5`,
  ['shop'] = 'pdm',
 },
 ['issi6'] = {
  ['name'] = 'Issi Nightmare',
  ['brand'] = 'Weeny',
  ['model'] = 'issi6',
  ['price'] = 80000,
  ['category'] = 'compacts',
  ['categoryLabel'] = 'Compacts',
  ['hash'] = `issi6`,
  ['shop'] = 'pdm',
 },
 ['panto'] = {
  ['name'] = 'Panto',
  ['brand'] = 'Benefactor',
  ['model'] = 'panto',
  ['price'] = 3200,
  ['category'] = 'compacts',
  ['categoryLabel'] = 'Compacts',
  ['hash'] = `panto`,
  ['shop'] = 'pdm',
 },
 ['prairie'] = {
  ['name'] = 'Prairie',
  ['brand'] = 'Bollokan',
  ['model'] = 'prairie',
  ['price'] = 30000,
  ['category'] = 'compacts',
  ['categoryLabel'] = 'Compacts',
  ['hash'] = `prairie`,
  ['shop'] = 'pdm',
 },
 ['rhapsody'] = {
  ['name'] = 'Rhapsody',
  ['brand'] = 'Declasse',
  ['model'] = 'rhapsody',
  ['price'] = 10000,
  ['category'] = 'compacts',
  ['categoryLabel'] = 'Compacts',
  ['hash'] = `rhapsody`,
  ['shop'] = 'pdm',
 },
 ['brioso2'] = {
  ['name'] = 'Brioso 300',
  ['brand'] = 'Grotti',
  ['model'] = 'brioso2',
  ['price'] = 12000,
  ['category'] = 'compacts',
  ['categoryLabel'] = 'Compacts',
  ['hash'] = `brioso2`,
  ['shop'] = 'pdm',
 },
 ['weevil'] = {
  ['name'] = 'Weevil',
  ['brand'] = 'BF',
  ['model'] = 'weevil',
  ['price'] = 9000,
  ['category'] = 'compacts',
  ['categoryLabel'] = 'Compacts',
  ['hash'] = `weevil`,
  ['shop'] = 'pdm',
 },
 ['blista2'] = {
  ['name'] = 'Blista Compact',
  ['brand'] = 'Dinka',
  ['model'] = 'blista2',
  ['price'] = 18950,
  ['category'] = 'compacts',
  ['categoryLabel'] = 'Compacts',
  ['hash'] = `blista2`,
  ['shop'] = 'pdm',
 },
 ['blista3'] = {
  ['name'] = 'Blista Go Go Monkey',
  ['brand'] = 'Dinka',
  ['model'] = 'blista3',
  ['price'] = 15000,
  ['category'] = 'compacts',
  ['categoryLabel'] = 'Compacts',
  ['hash'] = `blista3`,
  ['shop'] = 'pdm',
 },
 ['issi7'] = { --DLC
  ['name'] = 'Issi Sport',
  ['brand'] = 'Weeny',
  ['model'] = 'issi7',
  ['price'] = 100000,
  ['category'] = 'compacts',
  ['categoryLabel'] = 'Compacts',
  ['hash'] = `issi7`,
  ['shop'] = 'pdm',
 },
 ['brioso3'] = { --DLC +set sv_enforceGameBuild 2699 (and below)
  ['name'] = 'Brioso 300 Widebody',
  ['brand'] = 'Grotti',
  ['model'] = 'brioso3',
  ['price'] = 125000,
  ['category'] = 'compacts',
  ['categoryLabel'] = 'Compacts',
  ['hash'] = `brioso3`,
  ['shop'] = 'pdm',
 },
}