Config = Config or {}
Config.vehicles.coupes = {
 ['cogcabrio'] = {
  ['name'] = 'Cognoscenti Cabrio',
  ['brand'] = 'Enus',
  ['model'] = 'cogcabrio',
  ['price'] = 30000,
  ['category'] = 'coupes',
  ['categoryLabel'] = 'Coupes',
  ['hash'] = `cogcabrio`,
  ['shop'] = 'pdm',
 },
 ['exemplar'] = {
  ['name'] = 'Exemplar',
  ['brand'] = 'Dewbauchee',
  ['model'] = 'exemplar',
  ['price'] = 40000,
  ['category'] = 'coupes',
  ['categoryLabel'] = 'Coupes',
  ['hash'] = `exemplar`,
  ['shop'] = 'pdm',
 },
 ['f620'] = {
  ['name'] = 'F620',
  ['brand'] = 'Ocelot',
  ['model'] = 'f620',
  ['price'] = 32500,
  ['category'] = 'coupes',
  ['categoryLabel'] = 'Coupes',
  ['hash'] = `f620`,
  ['shop'] = 'pdm',
 },
 ['felon'] = {
  ['name'] = 'Felon',
  ['brand'] = 'Lampadati',
  ['model'] = 'felon',
  ['price'] = 31000,
  ['category'] = 'coupes',
  ['categoryLabel'] = 'Coupes',
  ['hash'] = `felon`,
  ['shop'] = 'pdm',
 },
 ['felon2'] = {
  ['name'] = 'Felon GT',
  ['brand'] = 'Lampadati',
  ['model'] = 'felon2',
  ['price'] = 37000,
  ['category'] = 'coupes',
  ['categoryLabel'] = 'Coupes',
  ['hash'] = `felon2`,
  ['shop'] = 'pdm',
 },
 ['jackal'] = {
  ['name'] = 'Jackal',
  ['brand'] = 'Ocelot',
  ['model'] = 'jackal',
  ['price'] = 19000,
  ['category'] = 'coupes',
  ['categoryLabel'] = 'Coupes',
  ['hash'] = `jackal`,
  ['shop'] = 'pdm',
 },
 ['oracle'] = {
  ['name'] = 'Oracle',
  ['brand'] = 'Übermacht',
  ['model'] = 'oracle',
  ['price'] = 22000,
  ['category'] = 'sedans',
  ['categoryLabel'] = 'Sedans',
  ['hash'] = `oracle`,
  ['shop'] = 'pdm',
 },
 ['oracle2'] = {
  ['name'] = 'Oracle XS',
  ['brand'] = 'Übermacht',
  ['model'] = 'oracle2',
  ['price'] = 28000,
  ['category'] = 'coupes',
  ['categoryLabel'] = 'Coupes',
  ['hash'] = `oracle2`,
  ['shop'] = 'pdm',
 },
 ['sentinel'] = {
  ['name'] = 'Sentinel',
  ['brand'] = 'Übermacht',
  ['model'] = 'sentinel',
  ['price'] = 30000,
  ['category'] = 'coupes',
  ['categoryLabel'] = 'Coupes',
  ['hash'] = `sentinel`,
  ['shop'] = 'pdm',
 },
 ['sentinel2'] = {
  ['name'] = 'Sentinel XS',
  ['brand'] = 'Übermacht',
  ['model'] = 'sentinel2',
  ['price'] = 33000,
  ['category'] = 'coupes',
  ['categoryLabel'] = 'Coupes',
  ['hash'] = `sentinel2`,
  ['shop'] = 'pdm',
 },
 ['windsor'] = {
  ['name'] = 'Windsor',
  ['brand'] = 'Enus',
  ['model'] = 'windsor',
  ['price'] = 27000,
  ['category'] = 'coupes',
  ['categoryLabel'] = 'Coupes',
  ['hash'] = `windsor`,
  ['shop'] = 'pdm',
 },
 ['windsor2'] = {
  ['name'] = 'Windsor Drop',
  ['brand'] = 'Enus',
  ['model'] = 'windsor2',
  ['price'] = 34000,
  ['category'] = 'coupes',
  ['categoryLabel'] = 'Coupes',
  ['hash'] = `windsor2`,
  ['shop'] = 'pdm',
 },
 ['zion'] = {
  ['name'] = 'Zion',
  ['brand'] = 'Übermacht',
  ['model'] = 'zion',
  ['price'] = 22000,
  ['category'] = 'coupes',
  ['categoryLabel'] = 'Coupes',
  ['hash'] = `zion`,
  ['shop'] = 'pdm',
 },
 ['zion2'] = {
  ['name'] = 'Zion Cabrio',
  ['brand'] = 'Übermacht',
  ['model'] = 'zion2',
  ['price'] = 28000,
  ['category'] = 'coupes',
  ['categoryLabel'] = 'Coupes',
  ['hash'] = `zion2`,
  ['shop'] = 'pdm',
 },
 ['previon'] = {
  ['name'] = 'Previon',
  ['brand'] = 'Karin',
  ['model'] = 'previon',
  ['price'] = 149000,
  ['category'] = 'coupes',
  ['categoryLabel'] = 'Coupes',
  ['hash'] = `previon`,
  ['shop'] = 'pdm',
 },
 ['champion'] = {
  ['name'] = 'Champion',
  ['brand'] = 'Dewbauchee',
  ['model'] = 'champion',
  ['price'] = 205000,
  ['category'] = 'coupes',
  ['categoryLabel'] = 'Coupes',
  ['hash'] = `champion`,
  ['shop'] = 'pdm',
 },
 ['ignus'] = {
  ['name'] = 'Ignus',
  ['brand'] = 'Pegassi',
  ['model'] = 'ignus',
  ['price'] = 1120000,
  ['category'] = 'coupes',
  ['categoryLabel'] = 'Coupes',
  ['hash'] = `ignus`,
  ['shop'] = 'pdm',
 },
 ['futo'] = {
  ['name'] = 'Futo',
  ['brand'] = 'Karin',
  ['model'] = 'futo',
  ['price'] = 17500,
  ['category'] = 'coupes',
  ['categoryLabel'] = 'Coupes',
  ['hash'] = `futo`,
  ['shop'] = 'pdm',
 },
 ['sentinel3'] = {
  ['name'] = 'Sentinel Classic',
  ['brand'] = 'Übermacht',
  ['model'] = 'sentinel3',
  ['price'] = 70000,
  ['category'] = 'coupes',
  ['categoryLabel'] = 'Coupes',
  ['hash'] = `sentinel3`,
  ['shop'] = 'pdm',
 },
 ['kanjosj'] = {
  ['name'] = 'Kanjo SJ',
  ['brand'] = 'Dinka',
  ['model'] = 'kanjosj',
  ['price'] = 143000,
  ['category'] = 'coupes',
  ['categoryLabel'] = 'Coupes',
  ['hash'] = `kanjosj`,
  ['shop'] = 'pdm',
 },
 ['postlude'] = {
  ['name'] = 'Postlude',
  ['brand'] = 'Dinka',
  ['model'] = 'postlude',
  ['price'] = 90000,
  ['category'] = 'coupes',
  ['categoryLabel'] = 'Coupes',
  ['hash'] = `postlude`,
  ['shop'] = 'pdm',
 },
}