Config = Config or {}
Config.vehciles.cycles = {
 ['bmx'] = {
  ['name'] = 'BMX',
  ['brand'] = 'Bike',
  ['model'] = 'bmx',
  ['price'] = 160,
  ['category'] = 'cycles',
  ['categoryLabel'] = 'Cycles',
  ['hash'] = `bmx`,
  ['shop'] = 'pdm',
 },
 ['cruiser'] = {
  ['name'] = 'Cruiser',
  ['brand'] = 'Bike',
  ['model'] = 'cruiser',
  ['price'] = 510,
  ['category'] = 'cycles',
  ['categoryLabel'] = 'Cycles',
  ['hash'] = `cruiser`,
  ['shop'] = 'pdm',
 },
 ['fixter'] = {
  ['name'] = 'Fixter',
  ['brand'] = 'Bike',
  ['model'] = 'fixter',
  ['price'] = 225,
  ['category'] = 'cycles',
  ['categoryLabel'] = 'Cycles',
  ['hash'] = `fixter`,
  ['shop'] = 'pdm',
 },
 ['scorcher'] = {
  ['name'] = 'Scorcher',
  ['brand'] = 'Bike',
  ['model'] = 'scorcher',
  ['price'] = 280,
  ['category'] = 'cycles',
  ['categoryLabel'] = 'Cycles',
  ['hash'] = `scorcher`,
  ['shop'] = 'pdm',
 },
 ['tribike'] = {
  ['name'] = 'Whippet Race Bike',
  ['brand'] = 'Bike',
  ['model'] = 'tribike',
  ['price'] = 500,
  ['category'] = 'cycles',
  ['categoryLabel'] = 'Cycles',
  ['hash'] = `tribike`,
  ['shop'] = 'pdm',
 },
 ['tribike2'] = {
  ['name'] = 'Endurex Race Bike',
  ['brand'] = 'Bike',
  ['model'] = 'tribike2',
  ['price'] = 700,
  ['category'] = 'cycles',
  ['categoryLabel'] = 'Cycles',
  ['hash'] = `tribike2`,
  ['shop'] = 'pdm',
 },
 ['tribike3'] = {
  ['name'] = 'Tri-Cycles Race Bike',
  ['brand'] = 'Bike',
  ['model'] = 'tribike3',
  ['price'] = 520,
  ['category'] = 'cycles',
  ['categoryLabel'] = 'Cycles',
  ['hash'] = `tribike3`,
  ['shop'] = 'pdm',
 },
}