Config = Config or {}
Config.vehicles.helicopters = {
 ['buzzard2'] = {
  ['name'] = 'Buzzard',
  ['brand'] = 'Unknown',
  ['model'] = 'buzzard2',
  ['price'] = 52000,
  ['category'] = 'helicopters',
  ['categoryLabel'] = 'Helicopters',
  ['hash'] = `buzzard2`,
  ['shop'] = 'air',
 },
 ['frogger'] = {
  ['name'] = 'Frogger',
  ['brand'] = 'Unknown',
  ['model'] = 'frogger',
  ['price'] = 52000,
  ['category'] = 'helicopters',
  ['categoryLabel'] = 'Helicopters',
  ['hash'] = `frogger`,
  ['shop'] = 'air',
 },
 ['frogger2'] = {
  ['name'] = 'Frogger (Trevor Philips Enterprises)',
  ['brand'] = 'Unknown',
  ['model'] = 'frogger2',
  ['price'] = 52000,
  ['category'] = 'helicopters',
  ['categoryLabel'] = 'Helicopters',
  ['hash'] = `frogger2`,
  ['shop'] = 'air',
 },
 ['maverick'] = {
  ['name'] = 'Maverick',
  ['brand'] = 'Unknown',
  ['model'] = 'maverick',
  ['price'] = 52000,
  ['category'] = 'helicopters',
  ['categoryLabel'] = 'Helicopters',
  ['hash'] = `maverick`,
  ['shop'] = 'air',
 },
 ['swift'] = {
  ['name'] = 'Swift',
  ['brand'] = 'Buckingham',
  ['model'] = 'swift',
  ['price'] = 52000,
  ['category'] = 'helicopters',
  ['categoryLabel'] = 'Helicopters',
  ['hash'] = `swift`,
  ['shop'] = 'air',
 },
 ['swift2'] = {
  ['name'] = 'Swift Deluxe',
  ['brand'] = 'Buckingham',
  ['model'] = 'swift2',
  ['price'] = 52000,
  ['category'] = 'helicopters',
  ['categoryLabel'] = 'Helicopters',
  ['hash'] = `swift2`,
  ['shop'] = 'air',
 },
 ['seasparrow'] = {
  ['name'] = 'Sea Sparrow',
  ['brand'] = 'Unknown',
  ['model'] = 'seasparrow',
  ['price'] = 52000,
  ['category'] = 'helicopters',
  ['categoryLabel'] = 'Helicopters',
  ['hash'] = `seasparrow`,
  ['shop'] = 'air',
 },
 ['seasparrow2'] = {
  ['name'] = 'Sparrow',
  ['brand'] = 'Unknown',
  ['model'] = 'seasparrow2',
  ['price'] = 52000,
  ['category'] = 'helicopters',
  ['categoryLabel'] = 'Helicopters',
  ['hash'] = `seasparrow2`,
  ['shop'] = 'air',
 },
 ['seasparrow3'] = {
  ['name'] = 'Sparrow (Prop)',
  ['brand'] = 'Unknown',
  ['model'] = 'seasparrow3',
  ['price'] = 52000,
  ['category'] = 'helicopters',
  ['categoryLabel'] = 'Helicopters',
  ['hash'] = `seasparrow3`,
  ['shop'] = 'air',
 },
 ['supervolito'] = {
  ['name'] = 'SuperVolito',
  ['brand'] = 'Buckingham',
  ['model'] = 'supervolito',
  ['price'] = 52000,
  ['category'] = 'helicopters',
  ['categoryLabel'] = 'Helicopters',
  ['hash'] = `supervolito`,
  ['shop'] = 'air',
 },
 ['supervolito2'] = {
  ['name'] = 'SuperVolito Carbon',
  ['brand'] = 'Buckingham',
  ['model'] = 'supervolito2',
  ['price'] = 52000,
  ['category'] = 'helicopters',
  ['categoryLabel'] = 'Helicopters',
  ['hash'] = `supervolito2`,
  ['shop'] = 'air',
 },
 ['volatus'] = {
  ['name'] = 'Volatus',
  ['brand'] = 'Buckingham',
  ['model'] = 'volatus',
  ['price'] = 52000,
  ['category'] = 'helicopters',
  ['categoryLabel'] = 'Helicopters',
  ['hash'] = `volatus`,
  ['shop'] = 'air',
 },
 ['havok'] = {
  ['name'] = 'Havok',
  ['brand'] = 'Nagasaki',
  ['model'] = 'havok',
  ['price'] = 52000,
  ['category'] = 'helicopters',
  ['categoryLabel'] = 'Helicopters',
  ['hash'] = `havok`,
  ['shop'] = 'air',
 },
 ['conada'] = {
  ['name'] = 'Conada',
  ['brand'] = 'Buckingham',
  ['model'] = 'conada',
  ['price'] = 115000,
  ['category'] = 'helicopters',
  ['categoryLabel'] = 'Helicopters',
  ['hash'] = `conada`,
  ['shop'] = 'air',
 },
}