Config = Config or {}
Config.vehicles.industrial = {
 ['cutter'] = {
  ['name'] = 'cutter',
  ['brand'] = 'HVY',
  ['model'] = 'cutter',
  ['price'] = 30000,
  ['category'] = 'industrial',
  ["categoryLabel"] = 'Industrial',
  ['hash'] = `cutter`,
  ['shop'] = 'truck',
 },
 ['handler'] = {
  ['name'] = 'Dock Handler',
  ['brand'] = 'HVY',
  ['model'] = 'handler',
  ['price'] = 30000,
  ['category'] = 'industrial',
  ["categoryLabel"] = 'Industrial',
  ['hash'] = `handler`,
  ['shop'] = 'truck',
 },
 ['bulldozer'] = {
  ['name'] = 'Bulldozer',
  ['brand'] = 'HVY',
  ['model'] = 'bulldozer',
  ['price'] = 30000,
  ['category'] = 'industrial',
  ["categoryLabel"] = 'Industrial',
  ['hash'] = `bulldozer`,
  ['shop'] = 'truck',
 },
 ['dump'] = {
  ['name'] = 'Dump Truck (Off Road)',
  ['brand'] = 'HVY',
  ['model'] = 'dump',
  ['price'] = 30000,
  ['category'] = 'industrial',
  ["categoryLabel"] = 'Industrial',
  ['hash'] = `dump`,
  ['shop'] = 'truck',
 },
 ['flatbed'] = {
  ['name'] = 'Flatbed Truck',
  ['brand'] = 'MTL',
  ['model'] = 'flatbed',
  ['price'] = 30000,
  ['category'] = 'industrial',
  ["categoryLabel"] = 'Industrial',
  ['hash'] = `flatbed`,
  ['shop'] = 'truck',
 },
 ['guardian'] = {
  ['name'] = 'Guardian',
  ['brand'] = 'Vapid',
  ['model'] = 'guardian',
  ['price'] = 30000,
  ['category'] = 'industrial',
  ["categoryLabel"] = 'Industrial',
  ['hash'] = `guardian`,
  ['shop'] = 'truck',
 },
 ['mixer'] = {
  ['name'] = 'Cement Mixer',
  ['brand'] = 'HVY',
  ['model'] = 'mixer',
  ['price'] = 30000,
  ['category'] = 'industrial',
  ["categoryLabel"] = 'Industrial',
  ['hash'] = `mixer`,
  ['shop'] = 'truck',
 },
 ['mixer2'] = {
  ['name'] = 'Cement Mixer 2',
  ['brand'] = 'HVY',
  ['model'] = 'mixer2',
  ['price'] = 30000,
  ['category'] = 'industrial',
  ["categoryLabel"] = 'Industrial',
  ['hash'] = `mixer2`,
  ['shop'] = 'truck',
 },
 ['rubble'] = {
  ['name'] = 'Dump Truck (Street Legal)',
  ['brand'] = 'Jobuilt',
  ['model'] = 'rubble',
  ['price'] = 30000,
  ['category'] = 'industrial',
  ["categoryLabel"] = 'Industrial',
  ['hash'] = `rubble`,
  ['shop'] = 'truck',
 },
 ['tiptruck'] = {
  ['name'] = 'Dump Truck (Street Legal)',
  ['brand'] = 'Brute',
  ['model'] = 'tiptruck',
  ['price'] = 30000,
  ['category'] = 'industrial',
  ["categoryLabel"] = 'Industrial',
  ['hash'] = `tiptruck`,
  ['shop'] = 'truck',
 },
 ['tiptruck2'] = {
  ['name'] = 'Dump Truck (Street Legal)',
  ['brand'] = 'MTL',
  ['model'] = 'tiptruck2',
  ['price'] = 30000,
  ['category'] = 'industrial',
  ["categoryLabel"] = 'Industrial',
  ['hash'] = `tiptruck2`,
  ['shop'] = 'truck',
 },
}