Config = Config or {}
Config.vehicles.motorcycles = {
 ['akuma'] = {
  ['name'] = 'Akuma',
  ['brand'] = 'Dinka',
  ['model'] = 'akuma',
  ['price'] = 55000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `akuma`,
  ['shop'] = 'pdm',
 },
 ['avarus'] = {
  ['name'] = 'Avarus',
  ['brand'] = 'LCC',
  ['model'] = 'avarus',
  ['price'] = 20000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `avarus`,
  ['shop'] = 'pdm',
 },
 ['bagger'] = {
  ['name'] = 'Bagger',
  ['brand'] = 'WMC',
  ['model'] = 'bagger',
  ['price'] = 13500,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `bagger`,
  ['shop'] = 'pdm',
 },
 ['bati'] = {
  ['name'] = 'Bati 801',
  ['brand'] = 'Pegassi',
  ['model'] = 'bati',
  ['price'] = 24000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `bati`,
  ['shop'] = 'pdm',
 },
 ['bati2'] = {
  ['name'] = 'Bati 801RR',
  ['brand'] = 'Pegassi',
  ['model'] = 'bati2',
  ['price'] = 19000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `bati2`,
  ['shop'] = 'pdm',
 },
 ['bf400'] = {
  ['name'] = 'BF400',
  ['brand'] = 'Nagasaki',
  ['model'] = 'bf400',
  ['price'] = 22000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `bf400`,
  ['shop'] = 'pdm',
 },
 ['carbonrs'] = {
  ['name'] = 'Carbon RS',
  ['brand'] = 'Nagasaki',
  ['model'] = 'carbonrs',
  ['price'] = 22000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `carbonrs`,
  ['shop'] = 'pdm',
 },
 ['chimera'] = {
  ['name'] = 'Chimera',
  ['brand'] = 'Nagasaki',
  ['model'] = 'chimera',
  ['price'] = 21000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `chimera`,
  ['shop'] = 'pdm',
 },
 ['cliffhanger'] = {
  ['name'] = 'Cliffhanger',
  ['brand'] = 'Western',
  ['model'] = 'cliffhanger',
  ['price'] = 28500,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `cliffhanger`,
  ['shop'] = 'pdm',
 },
 ['daemon'] = {
  ['name'] = 'Daemon',
  ['brand'] = 'WMC',
  ['model'] = 'daemon',
  ['price'] = 14000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `daemon`,
  ['shop'] = 'pdm',
 },
 ['daemon2'] = {
  ['name'] = 'Daemon Custom',
  ['brand'] = 'Western',
  ['model'] = 'daemon2',
  ['price'] = 23000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `daemon2`,
  ['shop'] = 'pdm',
 },
 ['defiler'] = {
  ['name'] = 'Defiler',
  ['brand'] = 'Shitzu',
  ['model'] = 'defiler',
  ['price'] = 30000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `defiler`,
  ['shop'] = 'pdm',
 },
 ['deathbike'] = { --DLC
  ['name'] = 'Deathbike Apocalypse',
  ['brand'] = 'Deathbike',
  ['model'] = 'deathbike',
  ['price'] = 30000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `deathbike`,
  ['shop'] = 'pdm',
 },
 ['deathbike2'] = { --DLC
  ['name'] = 'Deathbike Future Shock',
  ['brand'] = 'Deathbike',
  ['model'] = 'deathbike2',
  ['price'] = 30000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `deathbike2`,
  ['shop'] = 'pdm',
 },
 ['deathbike3'] = { --DLC
  ['name'] = 'Deathbike Nightmare',
  ['brand'] = 'Deathbike',
  ['model'] = 'deathbike3',
  ['price'] = 30000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `deathbike3`,
  ['shop'] = 'pdm',
 },
 ['diablous'] = {
  ['name'] = 'Diablous',
  ['brand'] = 'Principe',
  ['model'] = 'diablous',
  ['price'] = 30000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `diablous`,
  ['shop'] = 'pdm',
 },
 ['diablous2'] = {
  ['name'] = 'Diablous Custom',
  ['brand'] = 'Principe',
  ['model'] = 'diablous2',
  ['price'] = 38000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `diablous2`,
  ['shop'] = 'pdm',
 },
 ['double'] = {
  ['name'] = 'Double-T',
  ['brand'] = 'Dinka',
  ['model'] = 'double',
  ['price'] = 28000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `double`,
  ['shop'] = 'pdm',
 },
 ['enduro'] = {
  ['name'] = 'Enduro',
  ['brand'] = 'Dinka',
  ['model'] = 'enduro',
  ['price'] = 5500,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `enduro`,
  ['shop'] = 'pdm',
 },
 ['esskey'] = {
  ['name'] = 'Esskey',
  ['brand'] = 'Pegassi',
  ['model'] = 'esskey',
  ['price'] = 12000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `esskey`,
  ['shop'] = 'pdm',
 },
 ['faggio'] = {
  ['name'] = 'Faggio Sport',
  ['brand'] = 'Pegassi',
  ['model'] = 'faggio',
  ['price'] = 2000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `faggio`,
  ['shop'] = 'pdm',
 },
 ['faggio2'] = {
  ['name'] = 'Faggio',
  ['brand'] = 'Pegassi',
  ['model'] = 'faggio2',
  ['price'] = 1900,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `faggio2`,
  ['shop'] = 'pdm',
 },
 ['faggio3'] = {
  ['name'] = 'Faggio Mod',
  ['brand'] = 'Pegassi',
  ['model'] = 'faggio3',
  ['price'] = 2500,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `faggio3`,
  ['shop'] = 'pdm',
 },
 ['fcr'] = {
  ['name'] = 'FCR 1000',
  ['brand'] = 'Pegassi',
  ['model'] = 'fcr',
  ['price'] = 5000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `fcr`,
  ['shop'] = 'pdm',
 },
 ['fcr2'] = {
  ['name'] = 'FCR 1000 Custom',
  ['brand'] = 'Pegassi',
  ['model'] = 'fcr2',
  ['price'] = 19000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `fcr2`,
  ['shop'] = 'pdm',
 },
 ['gargoyle'] = {
  ['name'] = 'Gargoyle',
  ['brand'] = 'Western',
  ['model'] = 'gargoyle',
  ['price'] = 32000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `gargoyle`,
  ['shop'] = 'pdm',
 },
 ['hakuchou'] = {
  ['name'] = 'Hakuchou',
  ['brand'] = 'Shitzu',
  ['model'] = 'hakuchou',
  ['price'] = 17000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `hakuchou`,
  ['shop'] = 'pdm',
 },
 ['hakuchou2'] = {
  ['name'] = 'Hakuchou Drag',
  ['brand'] = 'Shitzu',
  ['model'] = 'hakuchou2',
  ['price'] = 45000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `hakuchou2`,
  ['shop'] = 'pdm',
 },
 ['hexer'] = {
  ['name'] = 'Hexer',
  ['brand'] = 'LCC',
  ['model'] = 'hexer',
  ['price'] = 16000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `hexer`,
  ['shop'] = 'pdm',
 },
 ['innovation'] = {
  ['name'] = 'Innovation',
  ['brand'] = 'LLC',
  ['model'] = 'innovation',
  ['price'] = 33500,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `innovation`,
  ['shop'] = 'pdm',
 },
 ['lectro'] = {
  ['name'] = 'Lectro',
  ['brand'] = 'Principe',
  ['model'] = 'lectro',
  ['price'] = 28000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `lectro`,
  ['shop'] = 'pdm',
 },
 ['manchez'] = {
  ['name'] = 'Manchez',
  ['brand'] = 'Maibatsu',
  ['model'] = 'manchez',
  ['price'] = 8300,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `manchez`,
  ['shop'] = 'pdm',
 },
 ['nemesis'] = {
  ['name'] = 'Nemesis',
  ['brand'] = 'Principe',
  ['model'] = 'nemesis',
  ['price'] = 20000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `nemesis`,
  ['shop'] = 'pdm',
 },
 ['nightblade'] = {
  ['name'] = 'Nightblade',
  ['brand'] = 'WMC',
  ['model'] = 'nightblade',
  ['price'] = 23000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `nightblade`,
  ['shop'] = 'pdm',
 },
 ['pcj'] = {
  ['name'] = 'PCJ-600',
  ['brand'] = 'Shitzu',
  ['model'] = 'pcj',
  ['price'] = 15000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `pcj`,
  ['shop'] = 'pdm',
 },
 ['ratbike'] = {
  ['name'] = 'Rat Bike',
  ['brand'] = 'Western',
  ['model'] = 'ratbike',
  ['price'] = 3000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `ratbike`,
  ['shop'] = 'pdm',
 },
 ['ruffian'] = {
  ['name'] = 'Ruffian',
  ['brand'] = 'Pegassi',
  ['model'] = 'ruffian',
  ['price'] = 25000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `ruffian`,
  ['shop'] = 'pdm',
 },
 ['sanchez'] = {
  ['name'] = 'Sanchez Livery',
  ['brand'] = 'Maibatsu',
  ['model'] = 'sanchez',
  ['price'] = 5300,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `sanchez`,
  ['shop'] = 'pdm',
 },
 ['sanchez2'] = {
  ['name'] = 'Sanchez',
  ['brand'] = 'Maibatsu',
  ['model'] = 'sanchez2',
  ['price'] = 5300,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `sanchez2`,
  ['shop'] = 'pdm',
 },
 ['sanctus'] = {
  ['name'] = 'Sanctus',
  ['brand'] = 'LCC',
  ['model'] = 'sanctus',
  ['price'] = 35000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `sanctus`,
  ['shop'] = 'pdm',
 },
 ['shotaro'] = {
  ['name'] = 'Shotaro',
  ['brand'] = 'Nagasaki',
  ['model'] = 'shotaro',
  ['price'] = 320000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `shotaro`,
  ['shop'] = 'pdm',
 },
 ['sovereign'] = {
  ['name'] = 'Sovereign',
  ['brand'] = 'WMC',
  ['model'] = 'sovereign',
  ['price'] = 8000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `sovereign`,
  ['shop'] = 'pdm',
 },
 ['stryder'] = {
  ['name'] = 'Stryder',
  ['brand'] = 'Nagasaki',
  ['model'] = 'stryder',
  ['price'] = 50000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `stryder`,
  ['shop'] = 'pdm',
 },
 ['thrust'] = {
  ['name'] = 'Thrust',
  ['brand'] = 'Dinka',
  ['model'] = 'thrust',
  ['price'] = 22000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `thrust`,
  ['shop'] = 'pdm',
 },
 ['vader'] = {
  ['name'] = 'Vader',
  ['brand'] = 'Shitzu',
  ['model'] = 'vader',
  ['price'] = 7200,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `vader`,
  ['shop'] = 'pdm',
 },
 ['vindicator'] = {
  ['name'] = 'Vindicator',
  ['brand'] = 'Dinka',
  ['model'] = 'vindicator',
  ['price'] = 19000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `vindicator`,
  ['shop'] = 'pdm',
 },
 ['vortex'] = {
  ['name'] = 'Vortex',
  ['brand'] = 'Pegassi',
  ['model'] = 'vortex',
  ['price'] = 31000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `vortex`,
  ['shop'] = 'pdm',
 },
 ['wolfsbane'] = {
  ['name'] = 'Wolfsbane',
  ['brand'] = 'Western',
  ['model'] = 'wolfsbane',
  ['price'] = 14000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `wolfsbane`,
  ['shop'] = 'pdm',
 },
 ['zombiea'] = {
  ['name'] = 'Zombie Bobber',
  ['brand'] = 'Western',
  ['model'] = 'zombiea',
  ['price'] = 28000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `zombiea`,
  ['shop'] = 'pdm',
 },
 ['zombieb'] = {
  ['name'] = 'Zombie Chopper',
  ['brand'] = 'Western',
  ['model'] = 'zombieb',
  ['price'] = 27000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `zombieb`,
  ['shop'] = 'pdm',
 },
 ['manchez2'] = {
  ['name'] = 'Manchez Scout',
  ['brand'] = 'Maibatsu',
  ['model'] = 'manchez2',
  ['price'] = 14000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `manchez2`,
  ['shop'] = 'pdm',
 },
 ['shinobi'] = {  --DLC +set sv_enforceGameBuild 2545
  ['name'] = 'Shinobi',
  ['brand'] = 'Nagasaki',
  ['model'] = 'shinobi',
  ['price'] = 25000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `shinobi`,
  ['shop'] = 'pdm',
 },
 ['reever'] = {  --DLC +set sv_enforceGameBuild 2545
  ['name'] = 'Reever',
  ['brand'] = 'Western',
  ['model'] = 'reever',
  ['price'] = 25000,
  ['category'] = 'motorcycles',
  ['categoryLabel'] = 'Motorcycles',
  ['hash'] = `reever`,
  ['shop'] = 'pdm',
 },
}