Config = Config or {}
Config.vehicles.muscle = {
 ['blade'] = {
  ['name'] = 'Blade',
  ['brand'] = 'Vapid',
  ['model'] = 'blade',
  ['price'] = 23500,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `blade`,
  ['shop'] = 'pdm',
 },
 ['buccaneer'] = {
  ['name'] = 'Buccaneer',
  ['brand'] = 'Albany',
  ['model'] = 'buccaneer',
  ['price'] = 22500,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `buccaneer`,
  ['shop'] = 'pdm',
 },
 ['buccaneer2'] = {
  ['name'] = 'Buccaneer Rider',
  ['brand'] = 'Albany',
  ['model'] = 'buccaneer2',
  ['price'] = 24500,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `buccaneer2`,
  ['shop'] = 'pdm',
 },
 ['chino'] = {
  ['name'] = 'Chino',
  ['brand'] = 'Vapid',
  ['model'] = 'chino',
  ['price'] = 5000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `chino`,
  ['shop'] = 'pdm',
 },
 ['chino2'] = {
  ['name'] = 'Chino Luxe',
  ['brand'] = 'Vapid',
  ['model'] = 'chino2',
  ['price'] = 8000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `chino2`,
  ['shop'] = 'pdm',
 },
 ['clique'] = { --DLC
  ['name'] = 'Clique',
  ['brand'] = 'Vapid',
  ['model'] = 'clique',
  ['price'] = 20000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `clique`,
  ['shop'] = 'pdm',
 },
 ['coquette3'] = {
  ['name'] = 'Coquette BlackFin',
  ['brand'] = 'Invetero',
  ['model'] = 'coquette3',
  ['price'] = 180000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `coquette3`,
  ['shop'] = 'pdm',
 },
 ['deviant'] = { --DLC
  ['name'] = 'Deviant',
  ['brand'] = 'Schyster',
  ['model'] = 'deviant',
  ['price'] = 70000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `deviant`,
  ['shop'] = 'pdm',
 },
 ['dominator'] = {
  ['name'] = 'Dominator',
  ['brand'] = 'Vapid',
  ['model'] = 'dominator',
  ['price'] = 62500,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `dominator`,
  ['shop'] = 'pdm',
 },
 ['dominator2'] = {
  ['name'] = 'Pißwasser Dominator',
  ['brand'] = 'Vapid',
  ['model'] = 'dominator2',
  ['price'] = 50000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `dominator2`,
  ['shop'] = 'pdm',
 },
 ['dominator3'] = {
  ['name'] = 'Dominator GTX',
  ['brand'] = 'Vapid',
  ['model'] = 'dominator3',
  ['price'] = 70000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `dominator3`,
  ['shop'] = 'pdm',
 },
 ['dominator4'] = { --DLC
  ['name'] = 'Dominator Arena',
  ['brand'] = 'Vapid',
  ['model'] = 'dominator4',
  ['price'] = 200000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `dominator4`,
  ['shop'] = 'pdm',
 },
 ['dominator7'] = { --DLC +set sv_enforceGameBuild 2372
  ['name'] = 'Dominator ASP',
  ['brand'] = 'Vapid',
  ['model'] = 'dominator7',
  ['price'] = 110000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `dominator7`,
  ['shop'] = 'pdm',
 },
 ['dominator8'] = { --DLC +set sv_enforceGameBuild 2372
  ['name'] = 'Dominator GTT',
  ['brand'] = 'Vapid',
  ['model'] = 'dominator8',
  ['price'] = 80000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `dominator8`,
  ['shop'] = 'pdm',
 },
 ['dukes'] = {
  ['name'] = 'Dukes',
  ['brand'] = 'Imponte',
  ['model'] = 'dukes',
  ['price'] = 23500,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `dukes`,
  ['shop'] = 'pdm',
 },
 ['dukes2'] = {
  ['name'] = 'Duke O\'Death',
  ['brand'] = 'Imponte',
  ['model'] = 'dukes2',
  ['price'] = 60000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `dukes2`,
  ['shop'] = 'pdm',
 },
 ['dukes3'] = {
  ['name'] = 'Beater Dukes',
  ['brand'] = 'Imponte',
  ['model'] = 'dukes3',
  ['price'] = 45000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `dukes3`,
  ['shop'] = 'pdm',
 },
 ['faction'] = {
  ['name'] = 'Faction',
  ['brand'] = 'Willard',
  ['model'] = 'faction',
  ['price'] = 17000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `faction`,
  ['shop'] = 'pdm',
 },
 ['faction2'] = {
  ['name'] = 'Faction Rider',
  ['brand'] = 'Willard',
  ['model'] = 'faction2',
  ['price'] = 19000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `faction2`,
  ['shop'] = 'pdm',
 },
 ['faction3'] = {
  ['name'] = 'Faction Custom Donk',
  ['brand'] = 'Willard',
  ['model'] = 'faction3',
  ['price'] = 35000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `faction3`,
  ['shop'] = 'pdm',
 },
 ['ellie'] = {
  ['name'] = 'Ellie',
  ['brand'] = 'Vapid',
  ['model'] = 'ellie',
  ['price'] = 42250,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `ellie`,
  ['shop'] = 'pdm',
 },
 ['gauntlet'] = {
  ['name'] = 'Gauntlet',
  ['brand'] = 'Bravado',
  ['model'] = 'gauntlet',
  ['price'] = 28500,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `gauntlet`,
  ['shop'] = 'pdm',
 },
 ['gauntlet2'] = {
  ['name'] = 'Redwood Gauntlet',
  ['brand'] = 'Bravado',
  ['model'] = 'gauntlet2',
  ['price'] = 70000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `gauntlet2`,
  ['shop'] = 'pdm',
 },
 ['gauntlet3'] = { --DLC
  ['name'] = 'Classic Gauntlet',
  ['brand'] = 'Bravado',
  ['model'] = 'gauntlet3',
  ['price'] = 75000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `gauntlet3`,
  ['shop'] = 'pdm',
 },
 ['gauntlet4'] = { --DLC
  ['name'] = 'Gauntlet Hellfire',
  ['brand'] = 'Bravado',
  ['model'] = 'gauntlet4',
  ['price'] = 80000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `gauntlet4`,
  ['shop'] = 'pdm',
 },
 ['gauntlet5'] = {
  ['name'] = 'Gauntlet Classic Custom',
  ['brand'] = 'Bravado',
  ['model'] = 'gauntlet5',
  ['price'] = 120000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `gauntlet5`,
  ['shop'] = 'pdm',
 },
 ['hermes'] = {
  ['name'] = 'Hermes',
  ['brand'] = 'Albany',
  ['model'] = 'hermes',
  ['price'] = 535000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `hermes`,
  ['shop'] = 'pdm',
 },
 ['hotknife'] = {
  ['name'] = 'Hotknife',
  ['brand'] = 'Vapid',
  ['model'] = 'hotknife',
  ['price'] = 90000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `hotknife`,
  ['shop'] = 'pdm',
 },
 ['hustler'] = {
  ['name'] = 'Hustler',
  ['brand'] = 'Vapid',
  ['model'] = 'hustler',
  ['price'] = 95000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `hustler`,
  ['shop'] = 'pdm',
 },
 ['impaler'] = { --DLC
  ['name'] = 'Impaler',
  ['brand'] = 'Vapid',
  ['model'] = 'impaler',
  ['price'] = 95000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `impaler`,
  ['shop'] = 'pdm',
 },
 ['impaler2'] = { --DLC
  ['name'] = 'Impaler Arena',
  ['brand'] = 'Vapid',
  ['model'] = 'impaler2',
  ['price'] = 95000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `impaler2`,
  ['shop'] = 'pdm',
 },
 ['impaler3'] = { --DLC
  ['name'] = 'Impaler Future Shock',
  ['brand'] = 'Vapid',
  ['model'] = 'impaler3',
  ['price'] = 95000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `impaler3`,
  ['shop'] = 'pdm',
 },
 ['impaler4'] = { --DLC
  ['name'] = 'Impaler Nightmare',
  ['brand'] = 'Vapid',
  ['model'] = 'impaler4',
  ['price'] = 95000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `impaler4`,
  ['shop'] = 'pdm',
 },
 ['imperator'] = { --DLC
  ['name'] = 'Imperator Arena',
  ['brand'] = 'Vapid',
  ['model'] = 'imperator',
  ['price'] = 95000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `imperator`,
  ['shop'] = 'pdm',
 },
 ['imperator2'] = { --DLC
  ['name'] = 'imperator Future Shock',
  ['brand'] = 'Vapid',
  ['model'] = 'imperator2',
  ['price'] = 95000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `imperator2`,
  ['shop'] = 'pdm',
 },
 ['imperator3'] = { --DLC
  ['name'] = 'Imperator Nightmare',
  ['brand'] = 'Vapid',
  ['model'] = 'imperator3',
  ['price'] = 95000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `imperator3`,
  ['shop'] = 'pdm',
 },
 ['lurcher'] = {
  ['name'] = 'Lurcher',
  ['brand'] = 'Bravado',
  ['model'] = 'lurcher',
  ['price'] = 21000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `lurcher`,
  ['shop'] = 'pdm',
 },
 ['nightshade'] = {
  ['name'] = 'Nightshade',
  ['brand'] = 'Imponte',
  ['model'] = 'nightshade',
  ['price'] = 70000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `nightshade`,
  ['shop'] = 'pdm',
 },
 ['phoenix'] = {
  ['name'] = 'Phoenix',
  ['brand'] = 'Imponte',
  ['model'] = 'phoenix',
  ['price'] = 65000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `phoenix`,
  ['shop'] = 'pdm',
 },
 ['picador'] = {
  ['name'] = 'Picador',
  ['brand'] = 'Cheval',
  ['model'] = 'picador',
  ['price'] = 20000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `picador`,
  ['shop'] = 'pdm',
 },
 ['ratloader2'] = {
  ['name'] = 'Ratloader',
  ['brand'] = 'Ratloader2',
  ['model'] = 'ratloader2',
  ['price'] = 20000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `ratloader2`,
  ['shop'] = 'pdm',
 },
 ['ruiner'] = {
  ['name'] = 'Ruiner',
  ['brand'] = 'Imponte',
  ['model'] = 'ruiner',
  ['price'] = 29000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `ruiner`,
  ['shop'] = 'pdm',
 },
 ['ruiner2'] = {
  ['name'] = 'Ruiner 2000',
  ['brand'] = 'Imponte',
  ['model'] = 'ruiner2',
  ['price'] = 50000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `ruiner2`,
  ['shop'] = 'pdm',
 },
 ['sabregt'] = {
  ['name'] = 'Sabre GT Turbo',
  ['brand'] = 'Declasse',
  ['model'] = 'sabregt',
  ['price'] = 23000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `sabregt`,
  ['shop'] = 'pdm',
 },
 ['sabregt2'] = {
  ['name'] = 'Sabre GT Turbo Custom',
  ['brand'] = 'Declasse',
  ['model'] = 'sabregt2',
  ['price'] = 26500,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `sabregt2`,
  ['shop'] = 'pdm',
 },
 ['slamvan'] = {
  ['name'] = 'Slam Van',
  ['brand'] = 'Vapid',
  ['model'] = 'slamvan',
  ['price'] = 30000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `slamvan`,
  ['shop'] = 'pdm',
 },
 ['slamvan2'] = {
  ['name'] = 'Lost Slam Van',
  ['brand'] = 'Vapid',
  ['model'] = 'slamvan2',
  ['price'] = 90000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `slamvan2`,
  ['shop'] = 'pdm',
 },
 ['slamvan3'] = {
  ['name'] = 'Slam Van Custom',
  ['brand'] = 'Vapid',
  ['model'] = 'slamvan3',
  ['price'] = 17000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `slamvan3`,
  ['shop'] = 'pdm',
 },
 ['stalion'] = {
  ['name'] = 'Stallion',
  ['brand'] = 'Declasse',
  ['model'] = 'stalion',
  ['price'] = 33000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `stalion`,
  ['shop'] = 'pdm',
 },
 ['stalion2'] = {
  ['name'] = 'Stallion Burgershot',
  ['brand'] = 'Declasse',
  ['model'] = 'stalion2',
  ['price'] = 40000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `stalion2`,
  ['shop'] = 'pdm',
 },
 ['tampa'] = {
  ['name'] = 'Tampa',
  ['brand'] = 'Declasse',
  ['model'] = 'tampa',
  ['price'] = 24500,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `tampa`,
  ['shop'] = 'pdm',
 },
 ['tulip'] = { --DLC
  ['name'] = 'Tulip',
  ['brand'] = 'Declasse',
  ['model'] = 'tulip',
  ['price'] = 80000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `tulip`,
  ['shop'] = 'pdm',
 },
 ['vamos'] = { --DLC
  ['name'] = 'Vamos',
  ['brand'] = 'Declasse',
  ['model'] = 'vamos',
  ['price'] = 30000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `vamos`,
  ['shop'] = 'pdm',
 },
 ['vigero'] = {
  ['name'] = 'Vigero',
  ['brand'] = 'Declasse',
  ['model'] = 'vigero',
  ['price'] = 39500,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `vigero`,
  ['shop'] = 'pdm',
 },
 ['virgo'] = {
  ['name'] = 'Virgo',
  ['brand'] = 'Albany',
  ['model'] = 'virgo',
  ['price'] = 22000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `virgo`,
  ['shop'] = 'pdm',
 },
 ['virgo2'] = {
  ['name'] = 'Virgo Custom Classic',
  ['brand'] = 'Dundreary',
  ['model'] = 'virgo2',
  ['price'] = 21000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `virgo2`,
  ['shop'] = 'pdm',
 },
 ['virgo3'] = {
  ['name'] = 'Virgo Classic',
  ['brand'] = 'Dundreary',
  ['model'] = 'virgo3',
  ['price'] = 21000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `virgo3`,
  ['shop'] = 'pdm',
 },
 ['voodoo'] = {
  ['name'] = 'Voodoo',
  ['brand'] = 'Declasse',
  ['model'] = 'voodoo',
  ['price'] = 13000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `voodoo`,
  ['shop'] = 'pdm',
 },
 ['yosemite'] = {
  ['name'] = 'Yosemite',
  ['brand'] = 'Declasse',
  ['model'] = 'yosemite',
  ['price'] = 19500,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `yosemite`,
  ['shop'] = 'pdm',
 },
 ['yosemite2'] = {
  ['name'] = 'Yosemite Drift',
  ['brand'] = 'Declasse',
  ['model'] = 'yosemite2',
  ['price'] = 55000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `yosemite2`,
  ['shop'] = 'pdm',
 },
 ['buffalo4'] = { --DLC +set sv_enforceGameBuild 2545
  ['name'] = 'Buffalo STX',
  ['brand'] = 'Bravado',
  ['model'] = 'buffalo4',
  ['price'] = 345000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `buffalo4`,
  ['shop'] = 'pdm',
 },
 ['tampa2'] = {
  ['name'] = 'Drift Tampa',
  ['brand'] = 'Declasse',
  ['model'] = 'tampa2',
  ['price'] = 80000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `tampa2`,
  ['shop'] = 'pdm',
 },
 ['manana'] = {
  ['name'] = 'Manana',
  ['brand'] = 'Albany',
  ['model'] = 'manana',
  ['price'] = 12800,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `manana`,
  ['shop'] = 'pdm',
 },
 ['manana2'] = {
  ['name'] = 'Manana Custom',
  ['brand'] = 'Albany',
  ['model'] = 'manana2',
  ['price'] = 24000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `manana2`,
  ['shop'] = 'pdm',
 },
 ['slamtruck'] = {
  ['name'] = 'Slam Truck',
  ['brand'] = 'Vapid',
  ['model'] = 'slamtruck',
  ['price'] = 100000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `slamtruck`,
  ['shop'] = 'pdm',
 },
 ['greenwood'] = {
  ['name'] = 'Greenwood',
  ['brand'] = 'Bravado',
  ['model'] = 'greenwood',
  ['price'] = 105000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `greenwood`,
  ['shop'] = 'pdm',
 },
 ['ruiner4'] = {
  ['name'] = 'Ruiner ZZ-8',
  ['brand'] = 'Imponte',
  ['model'] = 'ruiner4',
  ['price'] = 85000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `ruiner4`,
  ['shop'] = 'pdm',
 },
 ['vigero2'] = {
  ['name'] = 'Vigero ZX',
  ['brand'] = 'Declasse',
  ['model'] = 'vigero2',
  ['price'] = 105000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `vigero2`,
  ['shop'] = 'pdm',
 },
 ['weevil2'] = {
  ['name'] = 'Weevil Custom',
  ['brand'] = 'BF',
  ['model'] = 'weevil2',
  ['price'] = 95000,
  ['category'] = 'muscle',
  ['categoryLabel'] = 'Muscle',
  ['hash'] = `weevil2`,
  ['shop'] = 'pdm',
 },
}