Config = Config or {}
Config.vehicles.offRoad = {
 ['yosemite3'] = {
  ['name'] = 'Yosemite Rancher',
  ['brand'] = 'Declasse',
  ['price'] = 425000,
  ['category'] = 'offroad',
  ['categoryLabel'] = 'Off Road',
  ['model'] = 'yosemite3',
  ['hash'] = `yosemite3`,
  ['shop'] = 'pdm',
 },
 ['bfinjection'] = {
  ['name'] = 'Bf Injection',
  ['brand'] = 'Annis',
  ['price'] = 9000,
  ['category'] = 'offroad',
  ['categoryLabel'] = 'Off Road',
  ['model'] = 'bfinjection',
  ['hash'] = `bfinjection`,
  ['shop'] = 'pdm',
 },
 ['bifta'] = {
  ['name'] = 'Bifta',
  ['brand'] = 'Annis',
  ['price'] = 15500,
  ['category'] = 'offroad',
  ['categoryLabel'] = 'Off Road',
  ['model'] = 'bifta',
  ['hash'] = `bifta`,
  ['shop'] = 'pdm',
 },
 ['blazer'] = {
  ['name'] = 'Blazer',
  ['brand'] = 'Annis',
  ['price'] = 7500,
  ['category'] = 'offroad',
  ['categoryLabel'] = 'Off Road',
  ['model'] = 'blazer',
  ['hash'] = `blazer`,
  ['shop'] = 'pdm',
 },
 ['blazer2'] = {
  ['name'] = 'Blazer Lifeguard',
  ['brand'] = 'Nagasaki',
  ['model'] = 'blazer2',
  ['price'] = 7000,
  ['category'] = 'offroad',
  ['categoryLabel'] = 'Off Road',
  ['hash'] = `blazer2`,
  ['shop'] = 'pdm',
 },
 ['blazer3'] = {
  ['name'] = 'Blazer Hot Rod',
  ['brand'] = 'Nagasaki',
  ['model'] = 'blazer3',
  ['price'] = 7000,
  ['category'] = 'offroad',
  ['categoryLabel'] = 'Off Road',
  ['hash'] = `blazer3`,
  ['shop'] = 'pdm',
 },
 ['blazer4'] = {
  ['name'] = 'Blazer Sport',
  ['brand'] = 'Annis',
  ['price'] = 9250,
  ['category'] = 'offroad',
  ['categoryLabel'] = 'Off Road',
  ['model'] = 'blazer4',
  ['hash'] = `blazer4`,
  ['shop'] = 'pdm',
 },
 ['blazer5'] = {
  ['name'] = 'Blazer Aqua',
  ['brand'] = 'Nagasaki',
  ['model'] = 'blazer5',
  ['price'] = 40000,
  ['category'] = 'offroad',
  ['categoryLabel'] = 'Off Road',
  ['hash'] = `blazer5`,
  ['shop'] = 'pdm',
 },
 ['brawler'] = {
  ['name'] = 'Brawler',
  ['brand'] = 'Annis',
  ['price'] = 40000,
  ['category'] = 'offroad',
  ['categoryLabel'] = 'Off Road',
  ['model'] = 'brawler',
  ['hash'] = `brawler`,
  ['shop'] = 'pdm',
 },
 ['caracara'] = {
  ['name'] = 'Caracara',
  ['brand'] = 'Vapid',
  ['model'] = 'caracara',
  ['price'] = 60000,
  ['category'] = 'offroad',
  ['categoryLabel'] = 'Off Road',
  ['hash'] = `caracara`,
  ['shop'] = 'pdm',
 },
 ['caracara2'] = { --DLC
  ['name'] = 'Caracara 4x4',
  ['brand'] = 'Vapid',
  ['model'] = 'caracara2',
  ['price'] = 80000,
  ['category'] = 'offroad',
  ['categoryLabel'] = 'Off Road',
  ['hash'] = `caracara2`,
  ['shop'] = 'pdm',
 },
 ['dubsta3'] = {
  ['name'] = 'Dubsta 6x6',
  ['brand'] = 'Annis',
  ['price'] = 34000,
  ['category'] = 'offroad',
  ['categoryLabel'] = 'Off Road',
  ['model'] = 'dubsta3',
  ['hash'] = `dubsta3`,
  ['shop'] = 'pdm',
 },
 ['dune'] = {
  ['name'] = 'Dune Buggy',
  ['brand'] = 'Annis',
  ['price'] = 14000,
  ['category'] = 'offroad',
  ['categoryLabel'] = 'Off Road',
  ['model'] = 'dune',
  ['hash'] = `dune`,
  ['shop'] = 'pdm',
 },
 ['everon'] = {
  ['name'] = 'Everon',
  ['brand'] = 'Karin',
  ['model'] = 'everon',
  ['price'] = 60000,
  ['category'] = 'offroad',
  ['categoryLabel'] = 'Off Road',
  ['hash'] = `everon`,
  ['shop'] = 'pdm',
 },
 ['freecrawler'] = { --DLC
  ['name'] = 'Freecrawler',
  ['brand'] = 'Canis',
  ['model'] = 'freecrawler',
  ['price'] = 24000,
  ['category'] = 'offroad',
  ['categoryLabel'] = 'Off Road',
  ['hash'] = `freecrawler`,
  ['shop'] = 'pdm',
 },
 ['hellion'] = { --DLC
  ['name'] = 'Hellion',
  ['brand'] = 'Annis',
  ['model'] = 'hellion',
  ['price'] = 38000,
  ['category'] = 'offroad',
  ['categoryLabel'] = 'Off Road',
  ['hash'] = `hellion`,
  ['shop'] = 'pdm',
 },
 ['kalahari'] = {
  ['name'] = 'Kalahari',
  ['brand'] = 'Canis',
  ['model'] = 'kalahari',
  ['price'] = 14000,
  ['category'] = 'offroad',
  ['categoryLabel'] = 'Off Road',
  ['hash'] = `kalahari`,
  ['shop'] = 'pdm',
 },
 ['kamacho'] = {
  ['name'] = 'Kamacho',
  ['brand'] = 'Canis',
  ['model'] = 'kamacho',
  ['price'] = 50000,
  ['category'] = 'offroad',
  ['categoryLabel'] = 'Off Road',
  ['hash'] = `kamacho`,
  ['shop'] = 'pdm',
 },
 ['mesa3'] = {
  ['name'] = 'Mesa Merryweather',
  ['brand'] = 'Canis',
  ['model'] = 'mesa3',
  ['price'] = 400000,
  ['category'] = 'offroad',
  ['categoryLabel'] = 'Off Road',
  ['hash'] = `mesa3`,
  ['shop'] = 'pdm',
 },
 ['outlaw'] = {
  ['name'] = 'Outlaw',
  ['brand'] = 'Nagasaki',
  ['model'] = 'outlaw',
  ['price'] = 15000,
  ['category'] = 'offroad',
  ['categoryLabel'] = 'Off Road',
  ['hash'] = `outlaw`,
  ['shop'] = 'pdm',
 },
 ['rancherxl'] = {
  ['name'] = 'Rancher XL',
  ['brand'] = 'Declasse',
  ['model'] = 'rancherxl',
  ['price'] = 24000,
  ['category'] = 'offroad',
  ['categoryLabel'] = 'Off Road',
  ['hash'] = `rancherxl`,
  ['shop'] = 'pdm',
 },
 ['rebel2'] = {
  ['name'] = 'Rebel',
  ['brand'] = 'Vapid',
  ['model'] = 'rebel2',
  ['price'] = 20000,
  ['category'] = 'offroad',
  ['categoryLabel'] = 'Off Road',
  ['hash'] = `rebel2`,
  ['shop'] = 'pdm',
 },
 ['riata'] = {
  ['name'] = 'Riata',
  ['brand'] = 'Vapid',
  ['model'] = 'riata',
  ['price'] = 380000,
  ['category'] = 'offroad',
  ['categoryLabel'] = 'Off Road',
  ['hash'] = `riata`,
  ['shop'] = 'pdm',
 },
 ['sandking'] = {
  ['name'] = 'Sandking XL',
  ['brand'] = 'Vapid',
  ['price'] = 25000,
  ['category'] = 'offroad',
  ['categoryLabel'] = 'Off Road',
  ['model'] = 'sandking',
  ['hash'] = `sandking`,
  ['shop'] = 'pdm',
 },
 ['sandking2'] = {
  ['name'] = 'Sandking SWB',
  ['brand'] = 'Vapid',
  ['price'] = 38000,
  ['category'] = 'offroad',
  ['categoryLabel'] = 'Off Road',
  ['model'] = 'sandking2',
  ['hash'] = `sandking2`,
  ['shop'] = 'pdm',
 },
 ['trophytruck'] = {
  ['name'] = 'Trophy Truck',
  ['brand'] = 'Vapid',
  ['price'] = 60000,
  ['category'] = 'offroad',
  ['categoryLabel'] = 'Off Road',
  ['model'] = 'trophytruck',
  ['hash'] = `trophytruck`,
  ['shop'] = 'pdm',
 },
 ['trophytruck2'] = {
  ['name'] = 'Desert Raid',
  ['brand'] = 'Vapid',
  ['price'] = 80000,
  ['category'] = 'offroad',
  ['categoryLabel'] = 'Off Road',
  ['model'] = 'trophytruck2',
  ['hash'] = `trophytruck2`,
  ['shop'] = 'pdm',
 },
 ['vagrant'] = {
  ['name'] = 'Vagrant',
  ['brand'] = 'Maxwell',
  ['price'] = 50000,
  ['category'] = 'offroad',
  ['categoryLabel'] = 'Off Road',
  ['model'] = 'vagrant',
  ['hash'] = `vagrant`,
  ['shop'] = 'pdm',
 },
 ['verus'] = {
  ['name'] = 'Verus',
  ['brand'] = 'Dinka',
  ['price'] = 20000,
  ['category'] = 'offroad',
  ['categoryLabel'] = 'Off Road',
  ['model'] = 'verus',
  ['hash'] = `verus`,
  ['shop'] = 'pdm',
 },
 ['winky'] = {
  ['name'] = 'Winky',
  ['brand'] = 'Vapid',
  ['price'] = 10000,
  ['category'] = 'offroad',
  ['categoryLabel'] = 'Off Road',
  ['model'] = 'winky',
  ['hash'] = `winky`,
  ['shop'] = 'pdm',
 },
 ['mesa'] = {
  ['name'] = 'Mesa',
  ['brand'] = 'Canis',
  ['model'] = 'mesa',
  ['price'] = 12000,
  ['category'] = 'offroad',
  ['categoryLabel'] = 'Off Road',
  ['hash'] = `mesa`,
  ['shop'] = 'pdm',
 },
 ['sadler'] = {
  ['name'] = 'Sadler',
  ['brand'] = 'Vapid',
  ['model'] = 'sadler',
  ['price'] = 20000,
  ['category'] = 'offroad',
  ['categoryLabel'] = 'Off Road',
  ['hash'] = `sadler`,
  ['shop'] = 'pdm',
 },
 ['draugur'] = {
  ['name'] = 'Draugur',
  ['brand'] = 'Declasse',
  ['model'] = 'draugur',
  ['price'] = 99000,
  ['category'] = 'offroad',
  ['categoryLabel'] = 'Off Road',
  ['hash'] = `draugur`,
  ['shop'] = 'pdm',
 },
}