Config = Config or {}
Config.vehicles.planes = {
 ['duster'] = {
  ['name'] = 'Duster',
  ['brand'] = 'Unknown',
  ['model'] = 'duster',
  ['price'] = 45000,
  ['category'] = 'planes',
  ['categoryLabel'] = 'Planes',
  ['hash'] = `duster`,
  ['shop'] = 'air',
 },
 ['luxor'] = {
  ['name'] = 'Luxor',
  ['brand'] = 'Buckingham',
  ['model'] = 'luxor',
  ['price'] = 45000,
  ['category'] = 'planes',
  ['categoryLabel'] = 'Planes',
  ['hash'] = `luxor`,
  ['shop'] = 'air',
 },
 ['luxor2'] = {
  ['name'] = 'Luxor Deluxe',
  ['brand'] = 'Buckingham',
  ['model'] = 'luxor2',
  ['price'] = 45000,
  ['category'] = 'planes',
  ['categoryLabel'] = 'Planes',
  ['hash'] = `luxor2`,
  ['shop'] = 'air',
 },
 ['stunt'] = {
  ['name'] = 'Mallard',
  ['brand'] = 'Unknown',
  ['model'] = 'stunt',
  ['price'] = 45000,
  ['category'] = 'planes',
  ['categoryLabel'] = 'Planes',
  ['hash'] = `stunt`,
  ['shop'] = 'air',
 },
 ['mammatus'] = {
  ['name'] = 'Mammatus',
  ['brand'] = 'Unknown',
  ['model'] = 'mammatus',
  ['price'] = 45000,
  ['category'] = 'planes',
  ['categoryLabel'] = 'Planes',
  ['hash'] = `mammatus`,
  ['shop'] = 'air',
 },
 ['velum'] = {
  ['name'] = 'Velum',
  ['brand'] = 'Unknown',
  ['model'] = 'velum',
  ['price'] = 45000,
  ['category'] = 'planes',
  ['categoryLabel'] = 'Planes',
  ['hash'] = `velum`,
  ['shop'] = 'air',
 },
 ['velum2'] = {
  ['name'] = 'Velum 5-Seater',
  ['brand'] = 'Unknown',
  ['model'] = 'velum2',
  ['price'] = 45000,
  ['category'] = 'planes',
  ['categoryLabel'] = 'Planes',
  ['hash'] = `velum2`,
  ['shop'] = 'air',
 },
 ['shamal'] = {
  ['name'] = 'Shamal',
  ['brand'] = 'Buckingham',
  ['model'] = 'shamal',
  ['price'] = 45000,
  ['category'] = 'planes',
  ['categoryLabel'] = 'Planes',
  ['hash'] = `shamal`,
  ['shop'] = 'air',
 },
 ['vestra'] = {
  ['name'] = 'Vestra',
  ['brand'] = 'Buckingham',
  ['model'] = 'vestra',
  ['price'] = 45000,
  ['category'] = 'planes',
  ['categoryLabel'] = 'Planes',
  ['hash'] = `vestra`,
  ['shop'] = 'air',
 },
 ['dodo'] = {
  ['name'] = 'Dodo',
  ['brand'] = 'Mammoth',
  ['model'] = 'dodo',
  ['price'] = 45000,
  ['category'] = 'planes',
  ['categoryLabel'] = 'Planes',
  ['hash'] = `dodo`,
  ['shop'] = 'air',
 },
 ['howard'] = {
  ['name'] = 'Howard NX-25',
  ['brand'] = 'Buckingham',
  ['model'] = 'howard',
  ['price'] = 45000,
  ['category'] = 'planes',
  ['categoryLabel'] = 'Planes',
  ['hash'] = `howard`,
  ['shop'] = 'air',
 },
 ['alphaz1'] = {
  ['name'] = 'Alpha-Z1',
  ['brand'] = 'Buckingham',
  ['model'] = 'alphaz1',
  ['price'] = 45000,
  ['category'] = 'planes',
  ['categoryLabel'] = 'Planes',
  ['hash'] = `alphaz1`,
  ['shop'] = 'air',
 },
 ['nimbus'] = {
  ['name'] = 'Nimbus',
  ['brand'] = 'Buckingham',
  ['model'] = 'nimbus',
  ['price'] = 45000,
  ['category'] = 'planes',
  ['categoryLabel'] = 'Planes',
  ['hash'] = `nimbus`,
  ['shop'] = 'air',
 },
}