Config = Config or {}
Config.vehicles.sedans = {
 ['asea'] = {
  ['name'] = 'Asea',
  ['brand'] = 'Declasse',
  ['model'] = 'asea',
  ['price'] = 2500,
  ['category'] = 'sedans',
  ['categoryLabel'] = 'Sedans',
  ['hash'] = `asea`,
  ['shop'] = 'pdm',
 },
 ['asterope'] = {
  ['name'] = 'Asterope',
  ['brand'] = 'Karin',
  ['model'] = 'asterope',
  ['price'] = 11000,
  ['category'] = 'sedans',
  ['categoryLabel'] = 'Sedans',
  ['hash'] = `asterope`,
  ['shop'] = 'pdm',
 },
 ['cog55'] = {
  ['name'] = 'Cognoscenti 55',
  ['brand'] = 'Enus',
  ['model'] = 'cog55',
  ['price'] = 22000,
  ['category'] = 'sedans',
  ['categoryLabel'] = 'Sedans',
  ['hash'] = `cog55`,
  ['shop'] = 'pdm',
 },
 ['cognoscenti'] = {
  ['name'] = 'Cognoscenti',
  ['brand'] = 'Enus',
  ['model'] = 'cognoscenti',
  ['price'] = 22500,
  ['category'] = 'sedans',
  ['categoryLabel'] = 'Sedans',
  ['hash'] = `cognoscenti`,
  ['shop'] = 'pdm',
 },
 ['emperor'] = {
  ['name'] = 'Emperor',
  ['brand'] = 'Albany',
  ['model'] = 'emperor',
  ['price'] = 4250,
  ['category'] = 'sedans',
  ['categoryLabel'] = 'Sedans',
  ['hash'] = `emperor`,
  ['shop'] = 'pdm',
 },
 ['fugitive'] = {
  ['name'] = 'Fugitive',
  ['brand'] = 'Cheval',
  ['model'] = 'fugitive',
  ['price'] = 20000,
  ['category'] = 'sedans',
  ['categoryLabel'] = 'Sedans',
  ['hash'] = `fugitive`,
  ['shop'] = 'pdm',
 },
 ['glendale'] = {
  ['name'] = 'Glendale',
  ['brand'] = 'Benefactor',
  ['model'] = 'glendale',
  ['price'] = 3400,
  ['category'] = 'sedans',
  ['categoryLabel'] = 'Sedans',
  ['hash'] = `glendale`,
  ['shop'] = 'pdm',
 },
 ['glendale2'] = {
  ['name'] = 'Glendale Custom',
  ['brand'] = 'Benefactor',
  ['model'] = 'glendale2',
  ['price'] = 12000,
  ['category'] = 'sedans',
  ['categoryLabel'] = 'Sedans',
  ['hash'] = `glendale2`,
  ['shop'] = 'pdm',
 },
 ['ingot'] = {
  ['name'] = 'Ingot',
  ['brand'] = 'Vulcar',
  ['model'] = 'ingot',
  ['price'] = 4999,
  ['category'] = 'sedans',
  ['categoryLabel'] = 'Sedans',
  ['hash'] = `ingot`,
  ['shop'] = 'pdm',
 },
 ['intruder'] = {
  ['name'] = 'Intruder',
  ['brand'] = 'Karin',
  ['model'] = 'intruder',
  ['price'] = 11250,
  ['category'] = 'sedans',
  ['categoryLabel'] = 'Sedans',
  ['hash'] = `intruder`,
  ['shop'] = 'pdm',
 },
 ['premier'] = {
  ['name'] = 'Premier',
  ['brand'] = 'Declasse',
  ['model'] = 'premier',
  ['price'] = 12000,
  ['category'] = 'sedans',
  ['categoryLabel'] = 'Sedans',
  ['hash'] = `premier`,
  ['shop'] = 'pdm',
 },
 ['primo'] = {
  ['name'] = 'Primo',
  ['brand'] = 'Albany',
  ['model'] = 'primo',
  ['price'] = 5000,
  ['category'] = 'sedans',
  ['categoryLabel'] = 'Sedans',
  ['hash'] = `primo`,
  ['shop'] = 'pdm',
 },
 ['primo2'] = {
  ['name'] = 'Primo Custom',
  ['brand'] = 'Albany',
  ['model'] = 'primo2',
  ['price'] = 14500,
  ['category'] = 'sedans',
  ['categoryLabel'] = 'Sedans',
  ['hash'] = `primo2`,
  ['shop'] = 'pdm',
 },
 ['regina'] = {
  ['name'] = 'Regina',
  ['brand'] = 'Dundreary',
  ['model'] = 'regina',
  ['price'] = 7000,
  ['category'] = 'sedans',
  ['categoryLabel'] = 'Sedans',
  ['hash'] = `regina`,
  ['shop'] = 'pdm',
 },
 ['stafford'] = { --DLC
  ['name'] = 'Stafford',
  ['brand'] = 'Enus',
  ['model'] = 'stafford',
  ['price'] = 30000,
  ['category'] = 'sedans',
  ['categoryLabel'] = 'Sedans',
  ['hash'] = `stafford`,
  ['shop'] = 'pdm',
 },
 ['stanier'] = {
  ['name'] = 'Stanier',
  ['brand'] = 'Vapid',
  ['model'] = 'stanier',
  ['price'] = 19000,
  ['category'] = 'sedans',
  ['categoryLabel'] = 'Sedans',
  ['hash'] = `stanier`,
  ['shop'] = 'pdm',
 },
 ['stratum'] = {
  ['name'] = 'Stratum',
  ['brand'] = 'Zirconium',
  ['model'] = 'stratum',
  ['price'] = 15000,
  ['category'] = 'sedans',
  ['categoryLabel'] = 'Sedans',
  ['hash'] = `stratum`,
  ['shop'] = 'pdm',
 },
 ['stretch'] = {
  ['name'] = 'Stretch',
  ['brand'] = 'Dundreary',
  ['model'] = 'stretch',
  ['price'] = 19000,
  ['category'] = 'sedans',
  ['categoryLabel'] = 'Sedans',
  ['hash'] = `stretch`,
  ['shop'] = 'pdm',
 },
 ['superd'] = {
  ['name'] = 'Super Diamond',
  ['brand'] = 'Enus',
  ['model'] = 'superd',
  ['price'] = 17000,
  ['category'] = 'sedans',
  ['categoryLabel'] = 'Sedans',
  ['hash'] = `superd`,
  ['shop'] = 'pdm',
 },
 ['surge'] = {
  ['name'] = 'Surge',
  ['brand'] = 'Cheval',
  ['model'] = 'surge',
  ['price'] = 20000,
  ['category'] = 'sedans',
  ['categoryLabel'] = 'Sedans',
  ['hash'] = `surge`,
  ['shop'] = 'pdm',
 },
 ['tailgater'] = {
  ['name'] = 'Tailgater',
  ['brand'] = 'Obey',
  ['model'] = 'tailgater',
  ['price'] = 22000,
  ['category'] = 'sedans',
  ['categoryLabel'] = 'Sedans',
  ['hash'] = `tailgater`,
  ['shop'] = 'pdm',
 },
 ['warrener'] = {
  ['name'] = 'Warrener',
  ['brand'] = 'Vulcar',
  ['model'] = 'warrener',
  ['price'] = 4000,
  ['category'] = 'sedans',
  ['categoryLabel'] = 'Sedans',
  ['hash'] = `warrener`,
  ['shop'] = 'pdm',
 },
 ['washington'] = {
  ['name'] = 'Washington',
  ['brand'] = 'Albany',
  ['model'] = 'washington',
  ['price'] = 7000,
  ['category'] = 'sedans',
  ['categoryLabel'] = 'Sedans',
  ['hash'] = `washington`,
  ['shop'] = 'pdm',
 },
 ['tailgater2'] = { --DLC +set sv_enforceGameBuild 2372
  ['name'] = 'Tailgater S',
  ['brand'] = 'Obey',
  ['model'] = 'tailgater2',
  ['price'] = 51000,
  ['category'] = 'sedans',
  ['categoryLabel'] = 'Sedans',
  ['hash'] = `tailgater2`,
  ['shop'] = 'pdm',
 },
 ['cinquemila'] = { --DLC +set sv_enforceGameBuild 2545
  ['name'] = 'Lampadati',
  ['brand'] = 'Cinquemila',
  ['model'] = 'cinquemila',
  ['price'] = 125000,
  ['category'] = 'sedans',
  ['categoryLabel'] = 'Sedans',
  ['hash'] = `cinquemila`,
  ['shop'] = 'pdm',
 },
 ['iwagen'] = { --DLC +set sv_enforceGameBuild 2545
  ['name'] = 'Obey',
  ['brand'] = 'I-Wagen',
  ['model'] = 'iwagen',
  ['price'] = 225000,
  ['category'] = 'sedans',
  ['categoryLabel'] = 'Sedans',
  ['hash'] = `iwagen`,
  ['shop'] = 'pdm',
 },
 ['astron'] = { --DLC +set sv_enforceGameBuild 2545
  ['name'] = 'Astron',
  ['brand'] = 'Pfister',
  ['model'] = 'astron',
  ['price'] = 150000,
  ['category'] = 'sedans',
  ['categoryLabel'] = 'Sedans',
  ['hash'] = `astron`,
  ['shop'] = 'pdm',
 },
 ['baller7'] = { --DLC +set sv_enforceGameBuild 2545
  ['name'] = 'Baller ST',
  ['brand'] = 'Gallivanter',
  ['model'] = 'baller7',
  ['price'] = 145000,
  ['category'] = 'sedans',
  ['categoryLabel'] = 'Sedans',
  ['hash'] = `baller7`,
  ['shop'] = 'pdm',
 },
 ['comet7'] = { --DLC +set sv_enforceGameBuild 2545
  ['name'] = 'Comet',
  ['brand'] = 'S2 Cabrio',
  ['model'] = 'comet7',
  ['price'] = 25000,
  ['category'] = 'sedans',
  ['categoryLabel'] = 'Sedans',
  ['hash'] = `comet7`,
  ['shop'] = 'pdm',
 },
 ['deity'] = { --DLC +set sv_enforceGameBuild 2545
  ['name'] = 'Deity',
  ['brand'] = 'Enus',
  ['model'] = 'deity',
  ['price'] = 505000,
  ['category'] = 'sedans',
  ['categoryLabel'] = 'Sedans',
  ['hash'] = `deity`,
  ['shop'] = 'pdm',
 },
 ['jubilee'] = { --DLC +set sv_enforceGameBuild 2545
  ['name'] = 'Jubilee',
  ['brand'] = 'Enus',
  ['model'] = 'jubilee',
  ['price'] = 485000,
  ['category'] = 'sedans',
  ['categoryLabel'] = 'Sedans',
  ['hash'] = `jubilee`,
  ['shop'] = 'pdm',
 },
 ['schafter2'] = {
  ['name'] = 'Schafter',
  ['brand'] = 'Benefactor',
  ['model'] = 'schafter2',
  ['price'] = 16000,
  ['category'] = 'sedans',
  ['categoryLabel'] = 'Sedans',
  ['hash'] = `schafter2`,
  ['shop'] = 'pdm',
 },
 ['warrener2'] = { --DLC +set sv_enforceGameBuild 2372
  ['name'] = 'Warrener HKR',
  ['brand'] = 'Vulcar',
  ['model'] = 'warrener2',
  ['price'] = 30000,
  ['category'] = 'sedans',
  ['categoryLabel'] = 'Sedans',
  ['hash'] = `warrener2`,
  ['shop'] = 'pdm',
 },
 ['rhinehart'] = {
  ['name'] = 'Rhinehart',
  ['brand'] = 'Übermacht',
  ['model'] = 'rhinehart',
  ['price'] = 105000,
  ['category'] = 'sedans',
  ['categoryLabel'] = 'Sedans',
  ['hash'] = `rhinehart`,
  ['shop'] = 'pdm',
 },
}