Config = Config or {}
Config.vehicles.sports = {
 ['alpha'] = {
  ['name'] = 'Alpha',
  ['brand'] = 'Albany',
  ['model'] = 'alpha',
  ['price'] = 53000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `alpha`,
  ['shop'] = 'luxury',
 },
 ['banshee'] = {
  ['name'] = 'Banshee',
  ['brand'] = 'Bravado',
  ['model'] = 'banshee',
  ['price'] = 56000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `banshee`,
  ['shop'] = 'luxury',
 },
 ['bestiagts'] = {
  ['name'] = 'Bestia GTS',
  ['brand'] = 'Grotti',
  ['model'] = 'bestiagts',
  ['price'] = 37000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `bestiagts`,
  ['shop'] = 'luxury',
 },
 ['buffalo'] = {
  ['name'] = 'Buffalo',
  ['brand'] = 'Bravado',
  ['model'] = 'buffalo',
  ['price'] = 18750,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `buffalo`,
  ['shop'] = 'luxury',
 },
 ['buffalo2'] = {
  ['name'] = 'Buffalo S',
  ['brand'] = 'Bravado',
  ['model'] = 'buffalo2',
  ['price'] = 24500,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `buffalo2`,
  ['shop'] = 'luxury',
 },
 ['carbonizzare'] = {
  ['name'] = 'Carbonizzare',
  ['brand'] = 'Grotti',
  ['model'] = 'carbonizzare',
  ['price'] = 155000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `carbonizzare`,
  ['shop'] = 'luxury',
 },
 ['comet2'] = {
  ['name'] = 'Comet',
  ['brand'] = 'Pfister',
  ['model'] = 'comet2',
  ['price'] = 130000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `comet2`,
  ['shop'] = 'luxury',
 },
 ['comet3'] = {
  ['name'] = 'Comet Retro Custom',
  ['brand'] = 'Pfister',
  ['model'] = 'comet3',
  ['price'] = 175000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `comet3`,
  ['shop'] = 'luxury',
 },
 ['comet4'] = {
  ['name'] = 'Comet Safari',
  ['brand'] = 'Pfister',
  ['model'] = 'comet4',
  ['price'] = 110000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `comet4`,
  ['shop'] = 'luxury',
 },
 ['comet5'] = {
  ['name'] = 'Comet SR',
  ['brand'] = 'Pfister',
  ['model'] = 'comet5',
  ['price'] = 155000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `comet5`,
  ['shop'] = 'luxury',
 },
 ['coquette'] = {
  ['name'] = 'Coquette',
  ['brand'] = 'Invetero',
  ['model'] = 'coquette',
  ['price'] = 145000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `coquette`,
  ['shop'] = 'luxury',
 },
 ['coquette4'] = {
  ['name'] = 'Coquette D10',
  ['brand'] = 'Invetero',
  ['model'] = 'coquette4',
  ['price'] = 220000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `coquette4`,
  ['shop'] = 'luxury',
 },
 ['drafter'] = { --DLC
  ['name'] = '8F Drafter',
  ['brand'] = 'Obey',
  ['model'] = 'drafter',
  ['price'] = 80000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `drafter`,
  ['shop'] = 'luxury',
 },
 ['elegy'] = { --DLC
  ['name'] = 'Elegy Retro Custom',
  ['brand'] = 'Annis',
  ['model'] = 'elegy',
  ['price'] = 145000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `elegy`,
  ['shop'] = 'luxury',
 },
 ['elegy2'] = {
  ['name'] = 'Elegy RH8',
  ['brand'] = 'Annis',
  ['model'] = 'elegy2',
  ['price'] = 150000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `elegy2`,
  ['shop'] = 'luxury',
 },
 ['feltzer2'] = {
  ['name'] = 'Feltzer',
  ['brand'] = 'Benefactor',
  ['model'] = 'feltzer2',
  ['price'] = 97000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `feltzer2`,
  ['shop'] = 'luxury',
 },
 ['flashgt'] = {
  ['name'] = 'Flash GT',
  ['brand'] = 'Vapid',
  ['model'] = 'flashgt',
  ['price'] = 48000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `flashgt`,
  ['shop'] = 'luxury',
 },
 ['furoregt'] = {
  ['name'] = 'Furore GT',
  ['brand'] = 'Lampadati',
  ['model'] = 'furoregt',
  ['price'] = 78000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `furoregt`,
  ['shop'] = 'luxury',
 },
 ['gb200'] = {
  ['name'] = 'GB 200',
  ['brand'] = 'Vapid',
  ['model'] = 'gb200',
  ['price'] = 140000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `gb200`,
  ['shop'] = 'luxury',
 },
 ['komoda'] = {
  ['name'] = 'Komoda',
  ['brand'] = 'Lampadati',
  ['model'] = 'komoda',
  ['price'] = 55000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `komoda`,
  ['shop'] = 'luxury',
 },
 ['imorgon'] = {
  ['name'] = 'Imorgon',
  ['brand'] = 'Överflöd',
  ['model'] = 'imorgon',
  ['price'] = 120000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `imorgon`,
  ['shop'] = 'luxury',
 },
 ['italigto'] = { --DLC
  ['name'] = 'Itali GTO',
  ['brand'] = 'Progen',
  ['model'] = 'italigto',
  ['price'] = 260000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `italigto`,
  ['shop'] = 'luxury',
 },
 ['jugular'] = { --DLC
  ['name'] = 'Jugular',
  ['brand'] = 'Ocelot',
  ['model'] = 'jugular',
  ['price'] = 80000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `jugular`,
  ['shop'] = 'luxury',
 },
 ['jester'] = {
  ['name'] = 'Jester',
  ['brand'] = 'Dinka',
  ['model'] = 'jester',
  ['price'] = 132250,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `jester`,
  ['shop'] = 'luxury',
 },
 ['jester2'] = {
  ['name'] = 'Jester Racecar',
  ['brand'] = 'Dinka',
  ['model'] = 'jester2',
  ['price'] = 210000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `jester2`,
  ['shop'] = 'luxury',
 },
 ['jester3'] = {
  ['name'] = 'Jester Classic',
  ['brand'] = 'Dinka',
  ['model'] = 'jester3',
  ['price'] = 85000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `jester3`,
  ['shop'] = 'luxury',
 },
 ['khamelion'] = {
  ['name'] = 'Khamelion',
  ['brand'] = 'Hijak',
  ['model'] = 'khamelion',
  ['price'] = 90000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `khamelion`,
  ['shop'] = 'luxury',
 },
 ['kuruma'] = {
  ['name'] = 'Kuruma',
  ['brand'] = 'Karin',
  ['model'] = 'kuruma',
  ['price'] = 72000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `kuruma`,
  ['shop'] = 'luxury',
 },
 ['kuruma2'] = {
  ['name'] = 'kuruma2',
  ['brand'] = 'Karin2',
  ['model'] = 'kuruma2',
  ['price'] = 72000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `kuruma2`,
  ['shop'] = 'luxury',
 },
 ['locust'] = { --DLC
  ['name'] = 'Locust',
  ['brand'] = 'Ocelot',
  ['model'] = 'locust',
  ['price'] = 200000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `locust`,
  ['shop'] = 'luxury',
 },
 ['lynx'] = {
  ['name'] = 'Lynx',
  ['brand'] = 'Ocelot',
  ['model'] = 'lynx',
  ['price'] = 150000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `lynx`,
  ['shop'] = 'luxury',
 },
 ['massacro'] = {
  ['name'] = 'Massacro',
  ['brand'] = 'Dewbauchee',
  ['model'] = 'massacro',
  ['price'] = 110000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `massacro`,
  ['shop'] = 'luxury',
 },
 ['massacro2'] = {
  ['name'] = 'Massacro Racecar',
  ['brand'] = 'Dewbauchee',
  ['model'] = 'massacro2',
  ['price'] = 80000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `massacro2`,
  ['shop'] = 'luxury',
 },
 ['neo'] = { --DLC
  ['name'] = 'Neo',
  ['brand'] = 'Vysser',
  ['model'] = 'neo',
  ['price'] = 230000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `neo`,
  ['shop'] = 'luxury',
 },
 ['neon'] = { --DLC
  ['name'] = 'Neon',
  ['brand'] = 'Pfister',
  ['model'] = 'neon',
  ['price'] = 220000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `neon`,
  ['shop'] = 'luxury',
 },
 ['ninef'] = {
  ['name'] = '9F',
  ['brand'] = 'Obey',
  ['model'] = 'ninef',
  ['price'] = 95000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `ninef`,
  ['shop'] = 'luxury',
 },
 ['ninef2'] = {
  ['name'] = '9F Cabrio',
  ['brand'] = 'Obey',
  ['model'] = 'ninef2',
  ['price'] = 105000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `ninef2`,
  ['shop'] = 'luxury',
 },
 ['omnis'] = {
  ['name'] = 'Omnis',
  ['brand'] = 'Wow',
  ['model'] = 'omnis',
  ['price'] = 90000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `omnis`,
  ['shop'] = 'luxury',
 },
 ['paragon'] = { --DLC
  ['name'] = 'Paragon',
  ['brand'] = 'Enus',
  ['model'] = 'paragon',
  ['price'] = 60000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `paragon`,
  ['shop'] = 'luxury',
 },
 ['pariah'] = {
  ['name'] = 'Pariah',
  ['brand'] = 'Ocelot',
  ['model'] = 'pariah',
  ['price'] = 90000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `pariah`,
  ['shop'] = 'luxury',
 },
 ['penumbra'] = {
  ['name'] = 'Penumbra',
  ['brand'] = 'Maibatsu',
  ['model'] = 'penumbra',
  ['price'] = 22000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `penumbra`,
  ['shop'] = 'luxury',
 },
 ['penumbra2'] = {
  ['name'] = 'Penumbra FF',
  ['brand'] = 'Maibatsu',
  ['model'] = 'penumbra2',
  ['price'] = 30000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `penumbra2`,
  ['shop'] = 'luxury',
 },
 ['rapidgt'] = {
  ['name'] = 'Rapid GT',
  ['brand'] = 'Dewbauchee',
  ['model'] = 'rapidgt',
  ['price'] = 86000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `rapidgt`,
  ['shop'] = 'luxury',
 },
 ['rapidgt2'] = {
  ['name'] = 'Rapid GT Convertible',
  ['brand'] = 'Dewbauchee',
  ['model'] = 'rapidgt2',
  ['price'] = 92000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `rapidgt2`,
  ['shop'] = 'luxury',
 },
 ['raptor'] = {
  ['name'] = 'Raptor',
  ['brand'] = 'BF',
  ['model'] = 'raptor',
  ['price'] = 90000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `raptor`,
  ['shop'] = 'luxury',
 },
 ['revolter'] = {
  ['name'] = 'Revolter',
  ['brand'] = 'Übermacht',
  ['model'] = 'revolter',
  ['price'] = 95000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `revolter`,
  ['shop'] = 'luxury',
 },
 ['ruston'] = {
  ['name'] = 'Ruston',
  ['brand'] = 'Hijak',
  ['model'] = 'ruston',
  ['price'] = 130000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `ruston`,
  ['shop'] = 'luxury',
 },
 ['schafter3'] = {
  ['name'] = 'Schafter V12',
  ['brand'] = 'Benefactor',
  ['model'] = 'schafter3',
  ['price'] = 35000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `schafter3`,
  ['shop'] = 'luxury',
 },
 ['schafter4'] = {
  ['name'] = 'Schafter LWB',
  ['brand'] = 'Benefactor',
  ['model'] = 'schafter4',
  ['price'] = 21000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `schafter4`,
  ['shop'] = 'luxury',
 },
 ['schlagen'] = { --DLC
  ['name'] = 'Schlagen GT',
  ['brand'] = 'Benefactor',
  ['model'] = 'schlagen',
  ['price'] = 160000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `schlagen`,
  ['shop'] = 'luxury',
 },
 ['schwarzer'] = {
  ['name'] = 'Schwartzer',
  ['brand'] = 'Benefactor',
  ['model'] = 'schwarzer',
  ['price'] = 47000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `schwarzer`,
  ['shop'] = 'luxury',
 },
 ['seven70'] = {
  ['name'] = 'Seven-70',
  ['brand'] = 'Dewbauchee',
  ['model'] = 'seven70',
  ['price'] = 140000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `seven70`,
  ['shop'] = 'luxury',
 },
 ['specter'] = {
  ['name'] = 'Specter',
  ['brand'] = 'Dewbauchee',
  ['model'] = 'specter',
  ['price'] = 160000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `specter`,
  ['shop'] = 'luxury',
 },
 ['streiter'] = {
  ['name'] = 'Streiter',
  ['brand'] = 'Benefactor',
  ['model'] = 'streiter',
  ['price'] = 40000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `streiter`,
  ['shop'] = 'luxury',
 },
 ['sugoi'] = {
  ['name'] = 'Sugoi',
  ['brand'] = 'Dinka',
  ['model'] = 'sugoi',
  ['price'] = 85000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `sugoi`,
  ['shop'] = 'luxury',
 },
 ['sultan'] = {
  ['name'] = 'Sultan',
  ['brand'] = 'Karin',
  ['model'] = 'sultan',
  ['price'] = 50000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `sultan`,
  ['shop'] = 'luxury',
 },
 ['sultan2'] = {
  ['name'] = 'Sultan Custom',
  ['brand'] = 'Karin',
  ['model'] = 'sultan2',
  ['price'] = 55000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `sultan2`,
  ['shop'] = 'luxury',
 },
 ['surano'] = {
  ['name'] = 'Surano',
  ['brand'] = 'Benefactor',
  ['model'] = 'surano',
  ['price'] = 80000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `surano`,
  ['shop'] = 'luxury',
 },
 ['tropos'] = {
  ['name'] = 'Tropos Rallye',
  ['brand'] = 'Lampadati',
  ['model'] = 'tropos',
  ['price'] = 65000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `tropos`,
  ['shop'] = 'luxury',
 },
 ['verlierer2'] = {
  ['name'] = 'Verlierer',
  ['brand'] = 'Bravado',
  ['model'] = 'verlierer2',
  ['price'] = 90500,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `verlierer2`,
  ['shop'] = 'luxury',
 },
 ['vstr'] = {
  ['name'] = 'V-STR',
  ['brand'] = 'Albany',
  ['model'] = 'vstr',
  ['price'] = 80000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `vstr`,
  ['shop'] = 'luxury',
 },
 ['italirsx'] = {
  ['name'] = 'Itali RSX',
  ['brand'] = 'Progen',
  ['model'] = 'italirsx',
  ['price'] = 260000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `italirsx`,
  ['shop'] = 'luxury',
 },
 ['zr350'] = { --DLC +set sv_enforceGameBuild 2372
  ['name'] = 'ZR350',
  ['brand'] = 'Annis',
  ['model'] = 'zr350',
  ['price'] = 38000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `zr350`,
  ['shop'] = 'luxury',
 },
 ['calico'] = { --DLC +set sv_enforceGameBuild 2372
  ['name'] = 'Calico GTF',
  ['brand'] = 'Karin',
  ['model'] = 'calico',
  ['price'] = 39000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `calico`,
  ['shop'] = 'luxury',
 },
 ['futo2'] = { --DLC +set sv_enforceGameBuild 2372
  ['name'] = 'Futo GTX',
  ['brand'] = 'Karin',
  ['model'] = 'futo2',
  ['price'] = 39000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `futo2`,
  ['shop'] = 'luxury',
 },
 ['euros'] = { --DLC +set sv_enforceGameBuild 2372
  ['name'] = 'Euros',
  ['brand'] = 'Annis',
  ['model'] = 'euros',
  ['price'] = 80000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `euros`,
  ['shop'] = 'luxury',
 },
 ['jester4'] = { --DLC +set sv_enforceGameBuild 2372
  ['name'] = 'Jester RR',
  ['brand'] = 'Dinka',
  ['model'] = 'jester4',
  ['price'] = 240000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `jester4`,
  ['shop'] = 'luxury',
 },
 ['remus'] = { --DLC +set sv_enforceGameBuild 2372
  ['name'] = 'Remus',
  ['brand'] = 'Annis',
  ['model'] = 'remus',
  ['price'] = 48000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `remus`,
  ['shop'] = 'luxury',
 },
 ['comet6'] = { --DLC +set sv_enforceGameBuild 2372
  ['name'] = 'Comet S2',
  ['brand'] = 'Pfister',
  ['model'] = 'comet6',
  ['price'] = 230000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `comet6`,
  ['shop'] = 'luxury',
 },
 ['growler'] = { --DLC +set sv_enforceGameBuild 2372
  ['name'] = 'Growler',
  ['brand'] = 'Pfister',
  ['model'] = 'growler',
  ['price'] = 205000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `growler`,
  ['shop'] = 'luxury',
 },
 ['vectre'] = { --DLC +set sv_enforceGameBuild 2372
  ['name'] = 'Vectre',
  ['brand'] = 'Emperor',
  ['model'] = 'vectre',
  ['price'] = 80000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `vectre`,
  ['shop'] = 'luxury',
 },
 ['cypher'] = { --DLC +set sv_enforceGameBuild 2372
  ['name'] = 'Cypher',
  ['brand'] = 'Übermacht',
  ['model'] = 'cypher',
  ['price'] = 155000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `cypher`,
  ['shop'] = 'luxury',
 },
 ['sultan3'] = { --DLC +set sv_enforceGameBuild 2372
  ['name'] = 'Sultan Classic Custom',
  ['brand'] = 'Karin',
  ['model'] = 'sultan3',
  ['price'] = 56000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `sultan3`,
  ['shop'] = 'luxury',
 },
 ['rt3000'] = { --DLC +set sv_enforceGameBuild 2372
  ['name'] = 'RT3000',
  ['brand'] = 'Dinka',
  ['model'] = 'rt3000',
  ['price'] = 65000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `rt3000`,
  ['shop'] = 'luxury',
 },
 ['cheetah2'] = {
  ['name'] = 'Cheetah Classic',
  ['brand'] = 'Grotti',
  ['model'] = 'cheetah2',
  ['price'] = 195000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `cheetah2`,
  ['shop'] = 'luxury',
 },
 ['visione'] = {
  ['name'] = 'Visione',
  ['brand'] = 'Grotti',
  ['model'] = 'visione',
  ['price'] = 750000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `visione`,
  ['shop'] = 'luxury',
 },
 ['corsita'] = {
  ['name'] = 'Corsita',
  ['brand'] = 'Lampadati',
  ['model'] = 'corsita',
  ['price'] = 90000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `corsita`,
  ['shop'] = 'luxury',
 },
 ['omnisegt'] = {
  ['name'] = 'Omnis e-GT',
  ['brand'] = 'Obey',
  ['model'] = 'omnisegt',
  ['price'] = 185000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `omnisegt`,
  ['shop'] = 'luxury',
 },
 ['sentinel4'] = {
  ['name'] = 'Sentinel Classic Widebody',
  ['brand'] = 'Übermacht',
  ['model'] = 'sentinel4',
  ['price'] = 140000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `sentinel4`,
  ['shop'] = 'luxury',
 },
 ['sm722'] = {
  ['name'] = 'SM722',
  ['brand'] = 'Benefactor',
  ['model'] = 'sm722',
  ['price'] = 125000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `sm722`,
  ['shop'] = 'luxury',
 },
 ['tenf'] = {
  ['name'] = '10F',
  ['brand'] = 'Obey',
  ['model'] = 'tenf',
  ['price'] = 185000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `tenf`,
  ['shop'] = 'luxury',
 },
 ['tenf2'] = {
  ['name'] = '10F Widebody',
  ['brand'] = 'Obey',
  ['model'] = 'tenf2',
  ['price'] = 215000,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `tenf2`,
  ['shop'] = 'luxury',
 },
}