Config = Config or {}
Config.vehicles.sportsClassics = {
 ['peyote2'] = { --DLC
  ['name'] = 'Peyote Gasser',
  ['brand'] = 'Vapid',
  ['model'] = 'peyote2',
  ['price'] = 40000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `peyote2`,
  ['shop'] = 'pdm',
 },
 ['coquette2'] = {
  ['name'] = 'Coquette Classic',
  ['brand'] = 'Invetero',
  ['model'] = 'coquette2',
  ['price'] = 165000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `coquette2`,
  ['shop'] = 'pdm',
 },
 ['ardent'] = {
  ['name'] = 'Ardent',
  ['brand'] = 'Ocelot',
  ['model'] = 'ardent',
  ['price'] = 30000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `ardent`,
  ['shop'] = 'pdm',
 },
 ['btype'] = {  --meme car that goes pretty fast
  ['name'] = 'Roosevelt',
  ['brand'] = 'Albany',
  ['model'] = 'btype',
  ['price'] = 75000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `btype`,
  ['shop'] = 'pdm',
 },
 ['btype2'] = {
  ['name'] = 'Franken Stange',
  ['brand'] = 'Albany',
  ['model'] = 'btype2',
  ['price'] = 87000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `btype2`,
  ['shop'] = 'pdm',
 },
 ['btype3'] = {
  ['name'] = 'Roosevelt Valor',
  ['brand'] = 'Albany',
  ['model'] = 'btype3',
  ['price'] = 63000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `btype3`,
  ['shop'] = 'pdm',
 },
 ['casco'] = {
  ['name'] = 'Casco',
  ['brand'] = 'Lampadati',
  ['model'] = 'casco',
  ['price'] = 100000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `casco`,
  ['shop'] = 'pdm',
 },
 ['deluxo'] = {
  ['name'] = 'Deluxo',
  ['brand'] = 'Imponte',
  ['model'] = 'deluxo',
  ['price'] = 55000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `deluxo`,
  ['shop'] = 'pdm',
 },
 ['dynasty'] = { --DLC
  ['name'] = 'Dynasty',
  ['brand'] = 'Weeny',
  ['model'] = 'dynasty',
  ['price'] = 25000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `dynasty`,
  ['shop'] = 'pdm',
 },
 ['fagaloa'] = {
  ['name'] = 'Fagaloa',
  ['brand'] = 'Vulcar',
  ['model'] = 'fagaloa',
  ['price'] = 13000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `fagaloa`,
  ['shop'] = 'pdm',
 },
 ['feltzer3'] = { --DLC
  ['name'] = 'Stirling GT',
  ['brand'] = 'Benefactor',
  ['model'] = 'feltzer3',
  ['price'] = 115000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `feltzer3`,
  ['shop'] = 'pdm',
 },
 ['gt500'] = {
  ['name'] = 'GT500',
  ['brand'] = 'Grotti',
  ['model'] = 'gt500',
  ['price'] = 130000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `gt500`,
  ['shop'] = 'pdm',
 },
 ['infernus2'] = {
  ['name'] = 'Infernus Classic',
  ['brand'] = 'Pegassi',
  ['model'] = 'infernus2',
  ['price'] = 245000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `infernus2`,
  ['shop'] = 'pdm',
 },
 ['jb700'] = {
  ['name'] = 'JB 700',
  ['brand'] = 'Dewbauchee',
  ['model'] = 'jb700',
  ['price'] = 240000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `jb700`,
  ['shop'] = 'pdm',
 },
 ['jb7002'] = {
  ['name'] = 'JB 700W',
  ['brand'] = 'Dewbauchee',
  ['model'] = 'jb7002',
  ['price'] = 40000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `jb7002`,
  ['shop'] = 'pdm',
 },
 ['mamba'] = {
  ['name'] = 'Mamba',
  ['brand'] = 'Declasse',
  ['model'] = 'mamba',
  ['price'] = 140000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `mamba`,
  ['shop'] = 'pdm',
 },
 ['michelli'] = {
  ['name'] = 'Michelli GT',
  ['brand'] = 'Lampadati',
  ['model'] = 'michelli',
  ['price'] = 30000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `michelli`,
  ['shop'] = 'pdm',
 },
 ['monroe'] = {
  ['name'] = 'Monroe',
  ['brand'] = 'Pegassi',
  ['model'] = 'monroe',
  ['price'] = 115000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `monroe`,
  ['shop'] = 'pdm',
 },
 ['nebula'] = { --DLC
  ['name'] = 'Nebula',
  ['brand'] = 'Vulcar',
  ['model'] = 'nebula',
  ['price'] = 22000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `nebula`,
  ['shop'] = 'pdm',
 },
 ['peyote'] = {
  ['name'] = 'Peyote',
  ['brand'] = 'Vapid',
  ['model'] = 'peyote',
  ['price'] = 23500,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `peyote`,
  ['shop'] = 'pdm',
 },
 ['peyote3'] = {
  ['name'] = 'Peyote Custom',
  ['brand'] = 'Vapid',
  ['model'] = 'peyote3',
  ['price'] = 48000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `peyote3`,
  ['shop'] = 'pdm',
 },
 ['pigalle'] = {
  ['name'] = 'Pigalle',
  ['brand'] = 'Lampadati',
  ['model'] = 'pigalle',
  ['price'] = 92000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `pigalle`,
  ['shop'] = 'pdm',
 },
 ['rapidgt3'] = {
  ['name'] = 'Rapid GT Classic',
  ['brand'] = 'Dewbauchee',
  ['model'] = 'rapidgt3',
  ['price'] = 90000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `rapidgt3`,
  ['shop'] = 'pdm',
 },
 ['retinue'] = {
  ['name'] = 'Retinue',
  ['brand'] = 'Vapid',
  ['model'] = 'retinue',
  ['price'] = 32000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `retinue`,
  ['shop'] = 'pdm',
 },
 ['retinue2'] = {
  ['name'] = 'Retinue MKII',
  ['brand'] = 'Vapid',
  ['model'] = 'retinue2',
  ['price'] = 38000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `retinue2`,
  ['shop'] = 'pdm',
 },
 ['savestra'] = {
  ['name'] = 'Savestra',
  ['brand'] = 'Annis',
  ['model'] = 'savestra',
  ['price'] = 67000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `savestra`,
  ['shop'] = 'pdm',
 },
 ['stinger'] = {
  ['name'] = 'Stinger',
  ['brand'] = 'Grotti',
  ['model'] = 'stinger',
  ['price'] = 39500,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `stinger`,
  ['shop'] = 'pdm',
 },
 ['stingergt'] = {
  ['name'] = 'Stinger GT',
  ['brand'] = 'Grotti',
  ['model'] = 'stingergt',
  ['price'] = 70000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `stingergt`,
  ['shop'] = 'pdm',
 },
 ['stromberg'] = {
  ['name'] = 'Stromberg',
  ['brand'] = 'Ocelot',
  ['model'] = 'stromberg',
  ['price'] = 80000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `stromberg`,
  ['shop'] = 'pdm',
 },
 ['swinger'] = { --DLC
  ['name'] = 'Swinger',
  ['brand'] = 'Ocelot',
  ['model'] = 'swinger',
  ['price'] = 221000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `swinger`,
  ['shop'] = 'pdm',
 },
 ['torero'] = {
  ['name'] = 'Torero',
  ['brand'] = 'Pegassi',
  ['model'] = 'torero',
  ['price'] = 84000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `torero`,
  ['shop'] = 'pdm',
 },
 ['tornado'] = {
  ['name'] = 'Tornado',
  ['brand'] = 'Declasse',
  ['model'] = 'tornado',
  ['price'] = 21000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `tornado`,
  ['shop'] = 'pdm',
 },
 ['tornado2'] = {
  ['name'] = 'Tornado Convertible',
  ['brand'] = 'Declasse',
  ['model'] = 'tornado2',
  ['price'] = 22000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `tornado2`,
  ['shop'] = 'pdm',
 },
 ['tornado5'] = {
  ['name'] = 'Tornado Custom',
  ['brand'] = 'Declasse',
  ['model'] = 'tornado5',
  ['price'] = 22000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `tornado5`,
  ['shop'] = 'pdm',
 },
 ['turismo2'] = {
  ['name'] = 'Turismo Classic',
  ['brand'] = 'Grotti',
  ['model'] = 'turismo2',
  ['price'] = 170000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `turismo2`,
  ['shop'] = 'pdm',
 },
 ['viseris'] = {
  ['name'] = 'Viseris',
  ['brand'] = 'Lampadati',
  ['model'] = 'viseris',
  ['price'] = 210000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `viseris`,
  ['shop'] = 'pdm',
 },
 ['z190'] = {
  ['name'] = '190Z',
  ['brand'] = 'Karin',
  ['model'] = 'z190',
  ['price'] = 78000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `z190`,
  ['shop'] = 'pdm',
 },
 ['ztype'] = {
  ['name'] = 'Z-Type',
  ['brand'] = 'Truffade',
  ['model'] = 'ztype',
  ['price'] = 270000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `ztype`,
  ['shop'] = 'pdm',
 },
 ['zion3'] = { --DLC
  ['name'] = 'Zion Classic',
  ['brand'] = 'Übermacht',
  ['model'] = 'zion3',
  ['price'] = 45000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `zion3`,
  ['shop'] = 'pdm',
 },
 ['cheburek'] = {
  ['name'] = 'Cheburek',
  ['brand'] = 'Rune',
  ['model'] = 'cheburek',
  ['price'] = 7000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `cheburek`,
  ['shop'] = 'pdm',
 },
 ['toreador'] = {
  ['name'] = 'Toreador',
  ['brand'] = 'Pegassi',
  ['model'] = 'toreador',
  ['price'] = 50000,
  ['category'] = 'sportsclassics',
  ['categoryLabel'] = 'Sports Classics',
  ['hash'] = `toreador`,
  ['shop'] = 'pdm',
 },
}