Config = Config or {}
Config.vehicles.super = {
 ['zeno'] = {
  ['name'] = 'Zeno',
  ['brand'] = 'Överflöd',
  ['model'] = 'zeno',
  ['price'] = 1350000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `zeno`,
  ['shop'] = 'pdm',
 },
 ['oppressor'] = {
  ['name'] = 'Oppressor',
  ['brand'] = 'Pegassi',
  ['model'] = 'oppressor',
  ['price'] = 9999999,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `oppressor`,
  ['shop'] = 'luxury',
 },
 ['deveste'] = { --DLC
  ['name'] = 'Deveste',
  ['brand'] = 'Principe',
  ['model'] = 'deveste',
  ['price'] = 234000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `deveste`,
  ['shop'] = 'luxury',
 },
 ['adder'] = {
  ['name'] = 'Adder',
  ['brand'] = 'Truffade',
  ['model'] = 'adder',
  ['price'] = 280000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `adder`,
  ['shop'] = 'luxury',
 },
 ['autarch'] = {
  ['name'] = 'Autarch',
  ['brand'] = 'Överflöd',
  ['model'] = 'autarch',
  ['price'] = 224000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `autarch`,
  ['shop'] = 'luxury',
 },
 ['banshee2'] = {
  ['name'] = 'Banshee 900R',
  ['brand'] = 'Bravado',
  ['model'] = 'banshee2',
  ['price'] = 120000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `banshee2`,
  ['shop'] = 'luxury',
 },
 ['bullet'] = {
  ['name'] = 'Bullet',
  ['brand'] = 'Vapid',
  ['model'] = 'bullet',
  ['price'] = 120000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `bullet`,
  ['shop'] = 'luxury',
 },
 ['cheetah'] = {
  ['name'] = 'Cheetah',
  ['brand'] = 'Grotti',
  ['model'] = 'cheetah',
  ['price'] = 214000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `cheetah`,
  ['shop'] = 'luxury',
 },
 ['cyclone'] = {   --might be too overpowered
  ['name'] = 'Cyclone',
  ['brand'] = 'Coil',
  ['model'] = 'cyclone',
  ['price'] = 300000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `cyclone`,
  ['shop'] = 'luxury',
 },
 ['entity2'] = {
  ['name'] = 'Entity XXR',
  ['brand'] = 'Överflöd',
  ['model'] = 'entity2',
  ['price'] = 164000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `entity2`,
  ['shop'] = 'luxury',
 },
 ['entityxf'] = {
  ['name'] = 'Entity XF',
  ['brand'] = 'Överflöd',
  ['model'] = 'entityxf',
  ['price'] = 180000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `entityxf`,
  ['shop'] = 'luxury',
 },
 ['emerus'] = { --DLC
  ['name'] = 'Emerus',
  ['brand'] = 'Progen',
  ['model'] = 'emerus',
  ['price'] = 220000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `emerus`,
  ['shop'] = 'luxury',
 },
 ['fmj'] = {
  ['name'] = 'FMJ',
  ['brand'] = 'Vapid',
  ['model'] = 'fmj',
  ['price'] = 125000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `fmj`,
  ['shop'] = 'luxury',
 },
 ['furia'] = {
  ['name'] = 'Furia',
  ['brand'] = 'Grotti',
  ['model'] = 'furia',
  ['price'] = 230000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `furia`,
  ['shop'] = 'luxury',
 },
 ['gp1'] = {
  ['name'] = 'GP1',
  ['brand'] = 'Progen',
  ['model'] = 'gp1',
  ['price'] = 110000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `gp1`,
  ['shop'] = 'luxury',
 },
 ['infernus'] = {
  ['name'] = 'Infernus',
  ['brand'] = 'Pegassi',
  ['model'] = 'infernus',
  ['price'] = 235000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `infernus`,
  ['shop'] = 'luxury',
 },
 ['italigtb'] = {
  ['name'] = 'Itali GTB',
  ['brand'] = 'Progen',
  ['model'] = 'italigtb',
  ['price'] = 170000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `italigtb`,
  ['shop'] = 'luxury',
 },
 ['italigtb2'] = {
  ['name'] = 'Itali GTB Custom',
  ['brand'] = 'Progen',
  ['model'] = 'italigtb2',
  ['price'] = 250000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `italigtb2`,
  ['shop'] = 'luxury',
 },
 ['krieger'] = { --DLC
  ['name'] = 'Krieger',
  ['brand'] = 'Benefactor',
  ['model'] = 'krieger',
  ['price'] = 222000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `krieger`,
  ['shop'] = 'luxury',
 },
 ['le7b'] = {
  ['name'] = 'RE-7B',
  ['brand'] = 'Annis',
  ['model'] = 'le7b',
  ['price'] = 260000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `le7b`,
  ['shop'] = 'luxury',
 },
 ['nero'] = {
  ['name'] = 'Nero',
  ['brand'] = 'Truffade',
  ['model'] = 'nero',
  ['price'] = 200000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `nero`,
  ['shop'] = 'luxury',
 },
 ['nero2'] = {
  ['name'] = 'Nero Custom',
  ['brand'] = 'Truffade',
  ['model'] = 'nero2',
  ['price'] = 260000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `nero2`,
  ['shop'] = 'luxury',
 },
 ['osiris'] = {
  ['name'] = 'Osiris',
  ['brand'] = 'Pegassi',
  ['model'] = 'osiris',
  ['price'] = 220000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `osiris`,
  ['shop'] = 'luxury',
 },
 ['penetrator'] = {
  ['name'] = 'Penetrator',
  ['brand'] = 'Ocelot',
  ['model'] = 'penetrator',
  ['price'] = 130000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `penetrator`,
  ['shop'] = 'luxury',
 },
 ['pfister811'] = {
  ['name'] = '811',
  ['brand'] = 'Pfister',
  ['model'] = 'pfister811',
  ['price'] = 220000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `pfister811`,
  ['shop'] = 'luxury',
 },
 ['prototipo'] = {
  ['name'] = 'X80 Proto',
  ['brand'] = 'Grotti',
  ['model'] = 'prototipo',
  ['price'] = 235000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `prototipo`,
  ['shop'] = 'luxury',
 },
 ['reaper'] = {
  ['name'] = 'Reaper',
  ['brand'] = 'Pegassi',
  ['model'] = 'reaper',
  ['price'] = 100000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `reaper`,
  ['shop'] = 'luxury',
 },
 ['s80'] = { --DLC
  ['name'] = 'S80RR',
  ['brand'] = 'Annis',
  ['model'] = 's80',
  ['price'] = 205000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `s80`,
  ['shop'] = 'luxury',
 },
 ['sc1'] = {
  ['name'] = 'SC1',
  ['brand'] = 'Übermacht',
  ['model'] = 'sc1',
  ['price'] = 90000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `sc1`,
  ['shop'] = 'luxury',
 },
 ['sheava'] = { --DLC
  ['name'] = 'ETR1',
  ['brand'] = 'Emperor',
  ['model'] = 'sheava',
  ['price'] = 220000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `sheava`,
  ['shop'] = 'luxury',
 },
 ['sultanrs'] = {
  ['name'] = 'Sultan RS',
  ['brand'] = 'Karin',
  ['model'] = 'sultanrs',
  ['price'] = 76500,
  ['category'] = 'sports',
  ['categoryLabel'] = 'Sports',
  ['hash'] = `sultanrs`,
  ['shop'] = 'luxury',
 },
 ['t20'] = {
  ['name'] = 'T20',
  ['brand'] = 'Progen',
  ['model'] = 't20',
  ['price'] = 1650000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `t20`,
  ['shop'] = 'luxury',
 },
 ['taipan'] = {
  ['name'] = 'Taipan',
  ['brand'] = 'Cheval',
  ['model'] = 'taipan',
  ['price'] = 1850000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `taipan`,
  ['shop'] = 'luxury',
 },
 ['tempesta'] = {
  ['name'] = 'Tempesta',
  ['brand'] = 'Pegassi',
  ['model'] = 'tempesta',
  ['price'] = 120000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `tempesta`,
  ['shop'] = 'luxury',
 },
 ['tezeract'] = {
  ['name'] = 'Tezeract',
  ['brand'] = 'Pegassi',
  ['model'] = 'tezeract',
  ['price'] = 220000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `tezeract`,
  ['shop'] = 'luxury',
 },
 ['thrax'] = { --DLC
  ['name'] = 'Thrax',
  ['brand'] = 'Truffade',
  ['model'] = 'thrax',
  ['price'] = 180000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `thrax`,
  ['shop'] = 'luxury',
 },
 ['tigon'] = {
  ['name'] = 'Tigon',
  ['brand'] = 'Lampadati',
  ['model'] = 'tigon',
  ['price'] = 240000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `tigon`,
  ['shop'] = 'luxury',
 },
 ['turismor'] = {
  ['name'] = 'Turismo R',
  ['brand'] = 'Grotti',
  ['model'] = 'turismor',
  ['price'] = 140000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `turismor`,
  ['shop'] = 'luxury',
 },
 ['tyrant'] = {
  ['name'] = 'Tyrant',
  ['brand'] = 'Överflöd',
  ['model'] = 'tyrant',
  ['price'] = 2100000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `tyrant`,
  ['shop'] = 'luxury',
 },
 ['tyrus'] = {
  ['name'] = 'Tyrus',
  ['brand'] = 'Progen',
  ['model'] = 'tyrus',
  ['price'] = 230000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `tyrus`,
  ['shop'] = 'luxury',
 },
 ['vacca'] = {
  ['name'] = 'Vacca',
  ['brand'] = 'Pegassi',
  ['model'] = 'vacca',
  ['price'] = 105000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `vacca`,
  ['shop'] = 'luxury',
 },
 ['vagner'] = {
  ['name'] = 'Vagner',
  ['brand'] = 'Dewbauchee',
  ['model'] = 'vagner',
  ['price'] = 1660000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `vagner`,
  ['shop'] = 'luxury',
 },
 ['voltic'] = {
  ['name'] = 'Voltic',
  ['brand'] = 'Coil',
  ['model'] = 'voltic',
  ['price'] = 120000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `voltic`,
  ['shop'] = 'luxury',
 },
 ['voltic2'] = {
  ['name'] = 'Rocket Voltic',
  ['brand'] = 'Coil',
  ['model'] = 'voltic2',
  ['price'] = 9830400,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `voltic2`,
  ['shop'] = 'luxury',
 },
 ['xa21'] = {
  ['name'] = 'XA-21',
  ['brand'] = 'Ocelot',
  ['model'] = 'xa21',
  ['price'] = 180000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `xa21`,
  ['shop'] = 'luxury',
 },
 ['zentorno'] = {
  ['name'] = 'Zentorno',
  ['brand'] = 'Pegassi',
  ['model'] = 'zentorno',
  ['price'] = 340000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `zentorno`,
  ['shop'] = 'luxury',
 },
 ['zorrusso'] = { --DLC
  ['name'] = 'Zorrusso',
  ['brand'] = 'Pegassi',
  ['model'] = 'zorrusso',
  ['price'] = 277000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `zorrusso`,
  ['shop'] = 'luxury',
 },
 ['lm87'] = {
  ['name'] = 'LM87',
  ['brand'] = 'Benefactor',
  ['model'] = 'lm87',
  ['price'] = 155000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `lm87`,
  ['shop'] = 'luxury',
 },
 ['torero2'] = {
  ['name'] = 'Torero XO',
  ['brand'] = 'Pegassi',
  ['model'] = 'torero2',
  ['price'] = 245000,
  ['category'] = 'super',
  ['categoryLabel'] = 'Super',
  ['hash'] = `torero2`,
  ['shop'] = 'luxury',
 },
}