Config = Config or {}
Config.vehicles.suvs = {
 ['baller'] = {
  ['name'] = 'Baller',
  ['brand'] = 'Gallivanter',
  ['model'] = 'baller',
  ['price'] = 22000,
  ['category'] = 'suvs',
  ['categoryLabel'] = 'SUVs',
  ['hash'] = `baller`,
  ['shop'] = 'pdm',
 },
 ['baller2'] = {
  ['name'] = 'Baller II',
  ['brand'] = 'Gallivanter',
  ['model'] = 'baller2',
  ['price'] = 15000,
  ['category'] = 'suvs',
  ['categoryLabel'] = 'SUVs',
  ['hash'] = `baller2`,
  ['shop'] = 'pdm',
 },
 ['baller3'] = {
  ['name'] = 'Baller LE',
  ['brand'] = 'Gallivanter',
  ['model'] = 'baller3',
  ['price'] = 15000,
  ['category'] = 'suvs',
  ['categoryLabel'] = 'SUVs',
  ['hash'] = `baller3`,
  ['shop'] = 'pdm',
 },
 ['baller4'] = {
  ['name'] = 'Baller LE LWB',
  ['brand'] = 'Gallivanter',
  ['model'] = 'baller4',
  ['price'] = 29000,
  ['category'] = 'suvs',
  ['categoryLabel'] = 'SUVs',
  ['hash'] = `baller4`,
  ['shop'] = 'pdm',
 },
 ['baller5'] = {
  ['name'] = 'Baller LE (Armored)',
  ['brand'] = 'Gallivanter',
  ['model'] = 'baller5',
  ['price'] = 78000,
  ['category'] = 'suvs',
  ['categoryLabel'] = 'SUVs',
  ['hash'] = `baller5`,
  ['shop'] = 'pdm',
 },
 ['baller6'] = {
  ['name'] = 'Baller LE LWB (Armored)',
  ['brand'] = 'Gallivanter',
  ['model'] = 'baller6',
  ['price'] = 82000,
  ['category'] = 'suvs',
  ['categoryLabel'] = 'SUVs',
  ['hash'] = `baller6`,
  ['shop'] = 'pdm',
 },
 ['bjxl'] = {
  ['name'] = 'BeeJay XL',
  ['brand'] = 'Karin',
  ['model'] = 'bjxl',
  ['price'] = 19000,
  ['category'] = 'suvs',
  ['categoryLabel'] = 'SUVs',
  ['hash'] = `bjxl`,
  ['shop'] = 'pdm',
 },
 ['cavalcade'] = {
  ['name'] = 'Cavalcade',
  ['brand'] = 'Albany',
  ['model'] = 'cavalcade',
  ['price'] = 14000,
  ['category'] = 'suvs',
  ['categoryLabel'] = 'SUVs',
  ['hash'] = `cavalcade`,
  ['shop'] = 'pdm',
 },
 ['cavalcade2'] = {
  ['name'] = 'Cavalcade II',
  ['brand'] = 'Albany',
  ['model'] = 'cavalcade2',
  ['price'] = 16500,
  ['category'] = 'suvs',
  ['categoryLabel'] = 'SUVs',
  ['hash'] = `cavalcade2`,
  ['shop'] = 'pdm',
 },
 ['contender'] = {
  ['name'] = 'Contender',
  ['brand'] = 'Vapid',
  ['model'] = 'contender',
  ['price'] = 35000,
  ['category'] = 'suvs',
  ['categoryLabel'] = 'SUVs',
  ['hash'] = `contender`,
  ['shop'] = 'pdm',
 },
 ['dubsta'] = {
  ['name'] = 'Dubsta',
  ['brand'] = 'Benefactor',
  ['model'] = 'dubsta',
  ['price'] = 19000,
  ['category'] = 'suvs',
  ['categoryLabel'] = 'SUVs',
  ['hash'] = `dubsta`,
  ['shop'] = 'pdm',
 },
 ['dubsta2'] = {
  ['name'] = 'Dubsta Luxury',
  ['brand'] = 'Benefactor',
  ['model'] = 'dubsta2',
  ['price'] = 19500,
  ['category'] = 'suvs',
  ['categoryLabel'] = 'SUVs',
  ['hash'] = `dubsta2`,
  ['shop'] = 'pdm',
 },
 ['fq2'] = {
  ['name'] = 'FQ2',
  ['brand'] = 'Fathom',
  ['model'] = 'fq2',
  ['price'] = 18500,
  ['category'] = 'suvs',
  ['categoryLabel'] = 'SUVs',
  ['hash'] = `fq2`,
  ['shop'] = 'pdm',
 },
 ['granger'] = {
  ['name'] = 'Granger',
  ['brand'] = 'Declasse',
  ['model'] = 'granger',
  ['price'] = 22000,
  ['category'] = 'suvs',
  ['categoryLabel'] = 'SUVs',
  ['hash'] = `granger`,
  ['shop'] = 'pdm',
 },
 ['gresley'] = {
  ['name'] = 'Gresley',
  ['brand'] = 'Bravado',
  ['model'] = 'gresley',
  ['price'] = 25000,
  ['category'] = 'suvs',
  ['categoryLabel'] = 'SUVs',
  ['hash'] = `gresley`,
  ['shop'] = 'pdm',
 },
 ['habanero'] = {
  ['name'] = 'Habanero',
  ['brand'] = 'Emperor',
  ['model'] = 'habanero',
  ['price'] = 20000,
  ['category'] = 'suvs',
  ['categoryLabel'] = 'SUVs',
  ['hash'] = `habanero`,
  ['shop'] = 'pdm',
 },
 ['huntley'] = {
  ['name'] = 'Huntley S',
  ['brand'] = 'Enus',
  ['model'] = 'huntley',
  ['price'] = 24500,
  ['category'] = 'suvs',
  ['categoryLabel'] = 'SUVs',
  ['hash'] = `huntley`,
  ['shop'] = 'pdm',
 },
 ['landstalker'] = {
  ['name'] = 'Landstalker',
  ['brand'] = 'Dundreary',
  ['model'] = 'landstalker',
  ['price'] = 12000,
  ['category'] = 'suvs',
  ['categoryLabel'] = 'SUVs',
  ['hash'] = `landstalker`,
  ['shop'] = 'pdm',
 },
 ['landstalker2'] = {
  ['name'] = 'Landstalker XL',
  ['brand'] = 'Dundreary',
  ['model'] = 'landstalker2',
  ['price'] = 26000,
  ['category'] = 'suvs',
  ['categoryLabel'] = 'SUVs',
  ['hash'] = `landstalker2`,
  ['shop'] = 'pdm',
 },
  ['novak'] = { --DLC
  ['name'] = 'Novak',
  ['brand'] = 'Lampadati',
  ['model'] = 'novak',
  ['price'] = 70000,
  ['category'] = 'suvs',
  ['categoryLabel'] = 'SUVs',
  ['hash'] = `novak`,
  ['shop'] = 'pdm',
 },
 ['patriot'] = {
  ['name'] = 'Patriot',
  ['brand'] = 'Mammoth',
  ['model'] = 'patriot',
  ['price'] = 21000,
  ['category'] = 'suvs',
  ['categoryLabel'] = 'SUVs',
  ['hash'] = `patriot`,
  ['shop'] = 'pdm',
 },
 ['patriot2'] = {
  ['name'] = 'Patriot Stretch',
  ['brand'] = 'Mammoth',
  ['model'] = 'patriot2',
  ['price'] = 21000,
  ['category'] = 'suvs',
  ['categoryLabel'] = 'SUVs',
  ['hash'] = `patriot2`,
  ['shop'] = 'pdm',
 },
 ['radi'] = {
  ['name'] = 'Radius',
  ['brand'] = 'Vapid',
  ['model'] = 'radi',
  ['price'] = 18000,
  ['category'] = 'suvs',
  ['categoryLabel'] = 'SUVs',
  ['hash'] = `radi`,
  ['shop'] = 'pdm',
 },
 ['rebla'] = {
  ['name'] = 'Rebla GTS',
  ['brand'] = 'Übermacht',
  ['model'] = 'rebla',
  ['price'] = 21000,
  ['category'] = 'suvs',
  ['categoryLabel'] = 'SUVs',
  ['hash'] = `rebla`,
  ['shop'] = 'pdm',
 },
 ['rocoto'] = {
  ['name'] = 'Rocoto',
  ['brand'] = 'Obey',
  ['model'] = 'rocoto',
  ['price'] = 13000,
  ['category'] = 'suvs',
  ['categoryLabel'] = 'SUVs',
  ['hash'] = `rocoto`,
  ['shop'] = 'pdm',
 },
 ['seminole'] = {
  ['name'] = 'Seminole',
  ['brand'] = 'Canis',
  ['model'] = 'seminole',
  ['price'] = 20000,
  ['category'] = 'suvs',
  ['categoryLabel'] = 'SUVs',
  ['hash'] = `seminole`,
  ['shop'] = 'pdm',
 },
 ['seminole2'] = {
  ['name'] = 'Seminole Frontier',
  ['brand'] = 'Canis',
  ['model'] = 'seminole2',
  ['price'] = 13000,
  ['category'] = 'suvs',
  ['categoryLabel'] = 'SUVs',
  ['hash'] = `seminole2`,
  ['shop'] = 'pdm',
 },
 ['serrano'] = {
  ['name'] = 'Serrano',
  ['brand'] = 'Benefactor',
  ['model'] = 'serrano',
  ['price'] = 48000,
  ['category'] = 'suvs',
  ['categoryLabel'] = 'SUVs',
  ['hash'] = `serrano`,
  ['shop'] = 'pdm',
 },
 ['toros'] = { --DLC
  ['name'] = 'Toros',
  ['brand'] = 'Pegassi',
  ['model'] = 'toros',
  ['price'] = 65000,
  ['category'] = 'suvs',
  ['categoryLabel'] = 'SUVs',
  ['hash'] = `toros`,
  ['shop'] = 'pdm',
 },
 ['xls'] = {
  ['name'] = 'XLS',
  ['brand'] = 'Benefactor',
  ['model'] = 'xls',
  ['price'] = 17000,
  ['category'] = 'suvs',
  ['categoryLabel'] = 'SUVs',
  ['hash'] = `xls`,
  ['shop'] = 'pdm',
 },
 ['granger2'] = { --DLC +set sv_enforceGameBuild 2545
  ['name'] = 'Granger 3600LX',
  ['brand'] = 'Declasse',
  ['model'] = 'granger2',
  ['price'] = 221000,
  ['category'] = 'suvs',
  ['categoryLabel'] = 'SUVs',
  ['hash'] = `granger2`,
  ['shop'] = 'pdm',
 },
 ['patriot3'] = { --DLC +set sv_enforceGameBuild 2545
  ['name'] = 'Patriot Military',
  ['brand'] = 'Mil-Spec',
  ['model'] = 'patriot3',
  ['price'] = 270000,
  ['category'] = 'suvs',
  ['categoryLabel'] = 'SUVs',
  ['hash'] = `patriot3`,
  ['shop'] = 'pdm',
 },
}