Config = Config or {}
Config.vehicles.vans = {
 ['moonbeam'] = {
  ['name'] = 'Moonbeam',
  ['brand'] = 'Declasse',
  ['model'] = 'moonbeam',
  ['price'] = 13000,
  ['category'] = 'vans',
  ['categoryLabel'] = 'Vans',
  ['hash'] = `moonbeam`,
  ['shop'] = 'pdm',
 },
 ['moonbeam2'] = {
  ['name'] = 'Moonbeam Custom',
  ['brand'] = 'Declasse',
  ['model'] = 'moonbeam2',
  ['price'] = 15000,
  ['category'] = 'vans',
  ['categoryLabel'] = 'Vans',
  ['hash'] = `moonbeam2`,
  ['shop'] = 'pdm',
 },
 ['bison'] = {
  ['name'] = 'Bison',
  ['brand'] = 'Bravado',
  ['model'] = 'bison',
  ['price'] = 18000,
  ['category'] = 'vans',
  ['categoryLabel'] = 'Vans',
  ['hash'] = `bison`,
  ['shop'] = 'pdm',
 },
 ['bobcatxl'] = {
  ['name'] = 'Bobcat XL Open',
  ['brand'] = 'Vapid',
  ['model'] = 'bobcatxl',
  ['price'] = 13500,
  ['category'] = 'vans',
  ['categoryLabel'] = 'Vans',
  ['hash'] = `bobcatxl`,
  ['shop'] = 'pdm',
 },
 ['burrito3'] = {
  ['name'] = 'Burrito',
  ['brand'] = 'Declasse',
  ['model'] = 'burrito3',
  ['price'] = 4000,
  ['category'] = 'vans',
  ['categoryLabel'] = 'Vans',
  ['hash'] = `burrito3`,
  ['shop'] = 'pdm',
 },
 ['gburrito2'] = {
  ['name'] = 'Burrito Custom',
  ['brand'] = 'Declasse',
  ['model'] = 'gburrito2',
  ['price'] = 11500,
  ['category'] = 'vans',
  ['categoryLabel'] = 'Vans',
  ['hash'] = `gburrito2`,
  ['shop'] = 'pdm',
 },
 ['rumpo'] = {
  ['name'] = 'Rumpo',
  ['brand'] = 'Bravado',
  ['model'] = 'rumpo',
  ['price'] = 9000,
  ['category'] = 'vans',
  ['categoryLabel'] = 'Vans',
  ['hash'] = `rumpo`,
  ['shop'] = 'pdm',
 },
 ['journey'] = {
  ['name'] = 'Journey',
  ['brand'] = 'Zirconium',
  ['model'] = 'journey',
  ['price'] = 6500,
  ['category'] = 'vans',
  ['categoryLabel'] = 'Vans',
  ['hash'] = `journey`,
  ['shop'] = 'pdm',
 },
 ['minivan'] = {
  ['name'] = 'Minivan',
  ['brand'] = 'Vapid',
  ['model'] = 'minivan',
  ['price'] = 7000,
  ['category'] = 'vans',
  ['categoryLabel'] = 'Vans',
  ['hash'] = `minivan`,
  ['shop'] = 'pdm',
 },
 ['minivan2'] = {
  ['name'] = 'Minivan Custom',
  ['brand'] = 'Vapid',
  ['model'] = 'minivan2',
  ['price'] = 10000,
  ['category'] = 'vans',
  ['categoryLabel'] = 'Vans',
  ['hash'] = `minivan2`,
  ['shop'] = 'pdm',
 },
 ['paradise'] = {
  ['name'] = 'Paradise',
  ['brand'] = 'Bravado',
  ['model'] = 'paradise',
  ['price'] = 9000,
  ['category'] = 'vans',
  ['categoryLabel'] = 'Vans',
  ['hash'] = `paradise`,
  ['shop'] = 'pdm',
 },
 ['rumpo3'] = {
  ['name'] = 'Rumpo Custom',
  ['brand'] = 'Bravado',
  ['model'] = 'rumpo3',
  ['price'] = 19500,
  ['category'] = 'vans',
  ['categoryLabel'] = 'Vans',
  ['hash'] = `rumpo3`,
  ['shop'] = 'pdm',
 },
 ['speedo'] = {
  ['name'] = 'Speedo',
  ['brand'] = 'Vapid',
  ['model'] = 'speedo',
  ['price'] = 10000,
  ['category'] = 'vans',
  ['categoryLabel'] = 'Vans',
  ['hash'] = `speedo`,
  ['shop'] = 'pdm',
 },
 ['speedo4'] = {
  ['name'] = 'Speedo Custom',
  ['brand'] = 'Vapid',
  ['model'] = 'speedo4',
  ['price'] = 15000,
  ['category'] = 'vans',
  ['categoryLabel'] = 'Vans',
  ['hash'] = `speedo4`,
  ['shop'] = 'pdm',
 },
 ['surfer'] = {
  ['name'] = 'Surfer',
  ['brand'] = 'BF',
  ['model'] = 'surfer',
  ['price'] = 9000,
  ['category'] = 'vans',
  ['categoryLabel'] = 'Vans',
  ['hash'] = `surfer`,
  ['shop'] = 'pdm',
 },
 ['youga3'] = {
  ['name'] = 'Youga Classic 4x4',
  ['brand'] = 'Bravado',
  ['model'] = 'youga3',
  ['price'] = 15000,
  ['category'] = 'vans',
  ['categoryLabel'] = 'Vans',
  ['hash'] = `youga3`,
  ['shop'] = 'pdm',
 },
 ['youga'] = {
  ['name'] = 'Youga',
  ['brand'] = 'Bravado',
  ['model'] = 'youga',
  ['price'] = 8000,
  ['category'] = 'vans',
  ['categoryLabel'] = 'Vans',
  ['hash'] = `youga`,
  ['shop'] = 'pdm',
 },
 ['youga2'] = {
  ['name'] = 'Youga Classic',
  ['brand'] = 'Bravado',
  ['model'] = 'youga2',
  ['price'] = 14500,
  ['category'] = 'vans',
  ['categoryLabel'] = 'Vans',
  ['hash'] = `youga2`,
  ['shop'] = 'pdm',
 },
 ['youga4'] = { --DLC +set sv_enforceGameBuild 2545
  ['name'] = 'Youga Custom',
  ['brand'] = 'Bravado',
  ['model'] = 'youga4',
  ['price'] = 85000,
  ['category'] = 'vans',
  ['categoryLabel'] = 'Vans',
  ['hash'] = `youga4`,
  ['shop'] = 'pdm',
 },
 ['boxville'] = {
  ['name'] = 'Boxville LSDWP',
  ['brand'] = 'Brute',
  ['model'] = 'boxville',
  ['price'] = 45000,
  ['category'] = 'vans',
  ["categoryLabel"] = 'Vans',
  ['hash'] = `boxville`,
  ['shop'] = 'truck',
 },
 ['boxville2'] = {
  ['name'] = 'Boxville Go Postal',
  ['brand'] = 'Brute',
  ['model'] = 'boxville2',
  ['price'] = 45000,
  ['category'] = 'vans',
  ["categoryLabel"] = 'Vans',
  ['hash'] = `boxville2`,
  ['shop'] = 'truck',
 },
 ['boxville3'] = {
  ['name'] = 'Boxville Humane Labs',
  ['brand'] = 'Brute',
  ['model'] = 'boxville3',
  ['price'] = 45000,
  ['category'] = 'vans',
  ["categoryLabel"] = 'Vans',
  ['hash'] = `boxville3`,
  ['shop'] = 'truck',
 },
 ['boxville4'] = {
  ['name'] = 'Boxville Post OP',
  ['brand'] = 'Brute',
  ['model'] = 'boxville4',
  ['price'] = 45000,
  ['category'] = 'vans',
  ["categoryLabel"] = 'Vans',
  ['hash'] = `boxville4`,
  ['shop'] = 'truck',
 },
 ['boxville5'] = {
  ['name'] = 'Armored Boxville',
  ['brand'] = 'Brute',
  ['model'] = 'boxville5',
  ['price'] = 45000,
  ['category'] = 'vans',
  ["categoryLabel"] = 'Vans',
  ['hash'] = `boxville5`,
  ['shop'] = 'truck',
 },
 ['pony'] = {
  ['name'] = 'Pony',
  ['brand'] = 'Brute',
  ['model'] = 'pony',
  ['price'] = 45000,
  ['category'] = 'vans',
  ["categoryLabel"] = 'Vans',
  ['hash'] = `pony`,
  ['shop'] = 'truck',
 },
 ['pony2'] = {
  ['name'] = 'Pony (Smoke on the water)',
  ['brand'] = 'Brute',
  ['model'] = 'pony2',
  ['price'] = 45000,
  ['category'] = 'vans',
  ["categoryLabel"] = 'Vans',
  ['hash'] = `pony2`,
  ['shop'] = 'truck',
 },
 ['taco'] = {
  ['name'] = 'Taco Truck',
  ['brand'] = 'Brute',
  ['model'] = 'taco',
  ['price'] = 45000,
  ['category'] = 'vans',
  ["categoryLabel"] = 'Food Truck',
  ['hash'] = `taco`,
  ['shop'] = 'truck',
 },
}